### ISSUE TITLE
Bounty Tester: Connecting... Doesn't connect Win 10

### ISSUE THREAD

**Issue by Germuxas** [mysteriumnetwork/node#1034]
User:
Telegram name: @sfemat/Matteo

Hardware:
Win10
[MatteoGermosLog.zip](https://github.com/mysteriumnetwork/node/files/3156766/MatteoGermosLog.zip)
[Matteowin10.zip](https://github.com/mysteriumnetwork/node/files/3156767/Matteowin10.zip)

Comment: Had a working node, with a new build - can't connect.

Adding logs, mine as I was trying to connect and Matteo win10 logs.

**Comment by soffokl** [comment]
It looks like the same problem when OpenVPN session established, but Internet Connection Sharing(ICS) in Windows is not working. 

And the session was interrupted because of inactivity. 

No errors in the provider logs mean that all our command to enabled ICS has succeeded. But it didn't help to configure ICS.

The only strange thing I have found is a line:
`Nessuna regola corrispondente al criterio specificato.`

This means that Windows has the Italian language as a system default, but we were testing only with English versions as I know.

**Comment by ignasbernotas** [comment]
@soffokl are there language specific things in the powershell scripts? :O if so, maybe it's possible to set the language per-script?

**Comment by soffokl** [comment]
@ignasbernotas we are using interface name in the script, it could be something like `Подключение по локальной сети 3` instead of `Ethernet 3`.
I'm not totally sure if this will break the system since it was not tested.
