### ISSUE TITLE
NAT port mapping warning

### ISSUE THREAD

**Issue by idunno101** [mysteriumnetwork/node#1107]
When starting the node service I get a port mapping error that I'm not sure how to correct. I have port forwarding enabled for the addresses that are suggested in the output log.

[ProblemStart.txt](https://github.com/mysteriumnetwork/node/files/3219646/ProblemStart.txt)

The log shows that proposals are being pinged but it's not possible to connect to the node.

Here is also the output when the script is closed.

[ProblemClose.txt](https://github.com/mysteriumnetwork/node/files/3219651/ProblemClose.txt)

**Comment by zolia** [comment]
Hello, 

this warning is mare for informational purposes. 0.9 node release should support nat hole punching, thus manual forwarding is not strictly required. But with manual forwarding node will be more performant since packets will not be proxied inside node itself. 

Not to use nat hole punching, but remain with manual forwarding you should switch off nat hole punching: 
--experiment-natpunching=false

In your logs I don't see connect attempts. Did you try to connect from an app to your node?

**Comment by idunno101** [comment]
Thank you for the suggestions. I applied those and adjusted a couple of firewall rules and I can now successfully connect.
