### ISSUE TITLE
Analyse logs unreachable node xf784

### ISSUE THREAD

**Issue by RenatBuga** [mysteriumnetwork/node#1279]
This node is unreachable
https://testnet.mysterium.network/node/0xf784ce051e09b81085d96646c1d4c14eea64be68/openvpn

Logs attached.
[log2.log](https://github.com/mysteriumnetwork/node/files/3519674/log2.log)

**Comment by ignasbernotas** [comment]
@RenatBuga Can we get his ISP?

**Comment by ignasbernotas** [comment]
It is possible that his external IP address is shared amongst multiple ISP clients, therefore he isn't reachable externally. e.g. this ISP: https://www.hyperoptic.com/faq/posts/how-do-i-set-up-port-forwarding/

**Comment by RenatBuga** [comment]
@ignasbernotas ISP: Vodafone Limited

**Comment by osde8info** [comment]
please feel free to contact me directly about my bug :)

**Comment by ignasbernotas** [comment]
@osde8info thanks! could you to provide us with the logs around 2019-08-26 15:34 - 15:35 (UTC), I tried to connect to you just now, but there are no visible errors on the client side and the logs you provided are hard to correlate since we don't have the appropriate client logs. I'd be super grateful:) btw, it's strange that it was accessible earlier this month, but then just stopped working, maybe something changed with your ISP/node location? (just a guess:))

<img width="206" alt="Screenshot 2019-08-26 at 15 05 17" src="https://user-images.githubusercontent.com/402965/63702898-937dee80-c830-11e9-9080-348a5bb825d5.png">

**Comment by osde8info** [comment]
heres the output from

journalctl -u mysterium-node.service | egrep "^Aug 26 15:" > aug.log

[aug.log](https://github.com/mysteriumnetwork/node/files/3561208/aug.log)

**Comment by zolia** [comment]
Hello, 

looks like we can see an issue from these two lines:

Aug 20 00:09:58 raspberrypi myst[4458]: 2019-08-19T21:09:58.82469002 [Info] [core/discovery] stopping discovery loop..
Aug 20 00:09:58 raspberrypi myst[4458]: 2019-08-19T21:09:58.824805019 [Warn] [communication/nats/discovery] disconnected

Later on nats session disconnects and never reconnects. Thus we don't see any incoming client connect requests from broker.

This is probably triggered by service restart. Since no trace log available, hard to see the exact issue. 

We need to check if our service restart work as it is supposed to and we can get back to you on this.

**Comment by zolia** [comment]
I see continuous sessions active and availability 100% for this node. @osde8info do you still have issues running a node?

For further analysis we need more detailed log with trace level enabled: '--log-level trace'

**Comment by chompomonim** [comment]
Closing as no answer from bug reporter for long time.
