### ISSUE TITLE
Node is not connecting fully, sometimes it is disconnected.

### ISSUE THREAD

**Issue by Germuxas** [mysteriumnetwork/node#1355]
![ryan logs](https://user-images.githubusercontent.com/16088508/66899510-c314d000-f003-11e9-9102-a7515db4e785.png)
[Ryan_logs.zip](https://github.com/mysteriumnetwork/node/files/3733077/Ryan_logs.zip)

**Comment by zolia** [comment]
These logs state that node is being run 0.9.0 version on windows. This is fairly old node version which has many issues fixed since. Also, i don't see any attempts to connect to our discovery. 

ATM we do not support windows platform as such. Do you experience similar issues while running RPI node? Make sure that you have fairly decent mystberry image too.
