### ISSUE TITLE
Android app is loosing connection after changing connection from wifi to mobile

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1607]
I'm using 0.20.x version of android app. I can successfully connect to selected provider. When I'm changing connection type from WIFI to Mobile (e.g. going out of location when wifi is accessible), app still shows that I'm connected to VPN, but I can't really get any traffic (e.g. open web page in browser).

**Environment (please complete the following information):**
 - Node version: 0.20.0
 - OS: Android

**Comment by anjmao** [comment]
Also similar issues could appear on CLI or provider.

**Comment by cvl** [comment]
My experience on the matter:

When connected to VPN & WIFI -> switch off wifi (so cellular connection gets turned on).
The connection stops (perhaps because DNS server cannot be reached or other causes).
VPN app misleadingly stays connected. After 1-2 minutes, the app notification icon turns to "VPN disconnected", yet the built-in "Android System" notification still says VPN is activated. The VPN is actually on (just the notification icon misleads).

**Comment by anjmao** [comment]
So far after testing I get this issue for OpenVPN only. WireGuard works fine, but I'm testing in simulator for now.
@cvl I was able to fix it directly in android. You can check for https://github.com/mysteriumnetwork/mysterium-vpn-mobile/blob/master/android/app/src/main/java/network/mysterium/service/core/MysteriumAndroidCoreService.kt#L44 which returns object with Reconnect method which could be called on connection change when using OpenVPN. I will create a PR on ~Monday in android app repo.

**Comment by anjmao** [comment]
Should be fixed with https://github.com/mysteriumnetwork/mysterium-vpn-mobile/pull/183

**Comment by cvl** [comment]
@anjmao one thing:
if reconnect happens, the AppNotification doesn't catch this, as it's triggered only in SharedViewModel.connect

So App Notification says the connection is lost, when in fact it's on.

**Comment by cvl** [comment]
Also wondering, why notification isn't handled in the same fashion as label/button/stats in MainVpnFragment
