### ISSUE TITLE
how i can add other protocol to mysterium?

### ISSUE THREAD

**Issue by delokman** [mysteriumnetwork/node#1765]
i like to add some vpn protocol to mystream project
what steps i need to know?

**Comment by zolia** [comment]
Hello, 

thank you for your question. 

I will try to answer your question. By no means it will be exhaustive since adding new service to mysterium node is not very straight forward yet. 

Code itself evolves rapidly thus instructions might get outdated fast, but i will describe steps according current state of master branch. 

## major facilities

Before adding a new service to the node you need to decide which facilities of the network you want to use. Major facilities include: 
  - Identity registration - required ( ERC20 based identity used for secure communication and identification )
  - Proposal registration - required ( you announce your service to be discovered by others )
  - NAT traversal - optional ( If you want to run your service on nodes behind NAT routers )
  - Micro-payments  ( optional - if you will find nodes which would be willing to run such service for free )
  - Quality oracle - optional ( help to select proper node for consumer: help to evaluate node's service quality )

Now, you should decide which L3 protocols ( TCP or UDP ) your service will work on. NAT traversal is only available for UDP protocol at this point. 

## implementation key places

#### register cmd line flags for your service
_cmd/commands/cli/command.go:_
```go
config.RegisterFlagsServiceNewShinyService(&flags)
```
_cmd/commands/service/command.go_
```go 
config.RegisterFlagsServiceNewShinyService(flags)
```

#### register new service type
_cmd/commands/service/serviceTypes.go_
```go
serviceTypes = []string{"openvpn", "wireguard", "shiny", "noop"}
```

#### define service
_services/shiny/bootstrap.go_

```go
const ServiceType = "shiny"

// ServiceDefinition structure represents "shiny" service parameters
type ServiceDefinition struct {
	Location market.Location `json:"location"`
}
```

#### implement service
_services/shiny/service/service.go_
Implement at least: 
```go
func GetProposal(location location.Location) market.ServiceProposal
```

and following service interface:

``` go
type Service interface {
    Serve(instance *Instance) error
    Stop() error
    ProvideConfig(sessionID string, sessionConfig json.RawMessage) (*session.ConfigParams, error)
}
```

For more elaborate details you can check one of our currently supported services: openvpn, wireguard or noop (fake service for the sake of example)

### additional notes

 - When you launch node for the first time, identity is created and registered on blockchain automatically ( for testnet ) 
 - Proposals by default gets pinged (updated) every 3 minutes
 - The same code base is used for client side implementation too. Common workflow to connect to a service: 
     - register identity
     - unlock identity
     - get service proposals
     - select (filter) appropriate proposal
     - connect to service

## contribution

If you want your new node service to be included into node repo it has to comply with all practices used on node repo: code style, documentation, CI, unit tests, e2e tests etc. Best is to start with your own fork, put a PR and ask for review.

**Comment by Waldz** [comment]
Example how to bootstrap shiny service to `myst` node is here https://github.com/mysteriumnetwork/node/pull/1573
