### ISSUE TITLE
Whitelisting randomly changed

### ISSUE THREAD

**Issue by gitcloneguy** [mysteriumnetwork/node#1917]
I had the option to allow all traffic, i saved then one day, i came back to check and saw that it said allow only verified partner. i never touched the settings, it just changed by itself

Steps to reproduce:
1. Trying to change whitelisting option in WebUI from All traffic to the Mysterium verified, Saving.
2. Restarting service through WebUI changes whitelisting option in MMN
3. Restarting service with `sudo systemctl restart mysterium-node`doesn't change it

Expected behaviour:
config.toml file in /etc/mysterium-node/ should has the highest priorities in order of unexpected machine restart (or software update).

**Comment by etherunit** [comment]
Node identity id: 0x2f0ea27a8fd909470b0806614920c18ec1ab34bf

**Comment by sl00k** [comment]
changed from whitelisted to not whitelisted: 0xab8baa46fe8b868b850ccc443eaf75f6eda0b0e8

**Comment by gitcloneguy** [comment]
It just did it again

**Comment by sl00k** [comment]
with my node the option doesnt change.
but my node is not whitelisted, how do i solve it?

**Comment by samdave123** [comment]
0x3c484876777bb4c960723c3d14dfcfec3c3ae01c

Occurs after each updatel. I have to stop/start the service so it goes back to unwhitelistd.

**Comment by Waldz** [comment]
I investigated it, problem is with not respecting config priorities for flag `access-policy.list`
Linux daemon restarts with defaults value `--access-policy.list=""` and it's config.toml value `access-policy.list="mysterium"` loses priority.

I suggest to introduce some explicit e.g. `access-policy.list="*"` to avoid such problems in future.

**Comment by soffokl** [comment]
@Waldz you are not correct. Config has hight priority than the default arguments. 
Starting service with no flags read the value from the configuration file:
![image](https://user-images.githubusercontent.com/8612618/79033946-3c1c6b00-7bd4-11ea-9bba-0d427f40c31f.png)

And you don't need to investigate it since it resolved by https://github.com/mysteriumnetwork/mysterium-vpn-js/pull/39
And will be added to the node repo with a next WebUI update, which is in the https://github.com/mysteriumnetwork/dvpn-web/pull/88

**Comment by soffokl** [comment]
It's merged to master now. It will be released with the next version.
