### ISSUE TITLE
After disconnect DNS is not reset to default

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#2133]
**Current behaviour:**
On macOS I use `1.1.1.1` as my default DNS. After I connect to some node and disconnect my DNS is reset to routers default DNS.

**Expected behaviour**
Reset to previous set DNS.

**Comment by cvl** [comment]
Agreed!

**Comment by zolia** [comment]
Edge case flow looks like this: 
 - user starts a node
 - then, some point in time he decides to change his DNS, in this this case to 1.1.1.1
 - then he connects to some node provider
 - after disconnecting user expects that his computer will point to 1.1.1.1 DNS.

- [ ] This means we need to save current system DNS address(es) to persistence (bolt) on vpn connect and restore it on vpn disconnect.  

[ Task for supervisor ]

 - [ ] This is also a task for myst_supervisor since we need to check if there are no stale DNSes left on persistence and restore it if it does. 

 - [ ] use dns.ConfiguredServers() to get system DNS IPs, but does not work with windows atm. We can have it as a separate ticket, but we should do it too.
