### ISSUE TITLE
400 BAD REQUEST ON macOS

### ISSUE THREAD

**Issue by mrmindorg** [mysteriumnetwork/node#28]
Hello, some issues need help.

Node is running well, with **Ubuntu 17.04**.

Client is **macOS 10.12.5**, when I run this command 

> chmod +x mysterium_client_osx_amd64
> sudo ./mysterium_client_osx_amd64 --node=[THE NODE KEY]

It responses:

> Server response invalid: 400 BAD REQUEST

What's wrong with it?

**Comment by julien-blanchon** [comment]
Same issues.

**Comment by krisoul** [comment]
@mrmindorg Have u solved it?

**Comment by juanzolo** [comment]
Same

**Comment by JamesWuChina** [comment]
Now I am run the server side Same issues,i know the causes of the problem may be in the  .env  config MYSTERIUM_API_URL ,but i don't how to solved it.

**Comment by donce** [comment]
Hey @JamesWuChina, you have to be running api service, as described in [Step 3 in CONTRIBUTING.md](https://github.com/MysteriumNetwork/node/blob/master/CONTRIBUTING.md)

**Comment by zyfdegh** [comment]
I also got this error in latest builds. The mysterium node failed to start and printed these

```
server response invalid: 404 NOT FOUND (http://ca3.fanach.us:8001/identities) error message: {unknown API method}
```

It's caused by incompatible API routes between mysterium api-server and clients.

After I inspect the codes and I find the mysterium API server (https://github.com/MysteriumNetwork/api) provides an API `POST /v1/identities` but the clients call them without `v1/`, that's the root cause resulting a 404 not found error.

**Comment by zyfdegh** [comment]
Fixed by appending  **`v1/`** to the URL in `.env`. 
So, finally it will be something like this `MYSTERIUM_API_URL=http://my.hostname.com:8001/v1`

**Comment by donce** [comment]
@zyfdegh maybe you want to improve [CONTRIBUTING.md](https://github.com/MysteriumNetwork/node/blob/master/CONTRIBUTING.md) to clarify this? :)

**Comment by zyfdegh** [comment]
Sure, I will. @donce
