### ISSUE TITLE
Can't save price settings via WebUI 

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2880]
Using node v0.40.3. 
Install into Ubuntu 20.04 via `apt install mys`.

![Screenshot 2020-12-01 at 23 07 55](https://user-images.githubusercontent.com/153896/100797660-2a215e00-342b-11eb-96fc-370d401b7d6a.png)

**Comment by tomasmik** [comment]
Does this issue still exist with the current release? I've tested it in version 0.41.0-pre
 and found nothing like this. Got a node running with custom prices:
```
| Identity: 0x105b3d9f7008d9bc7d825572a60946cc8fc9705d | Type: hosting | Country: NL | Price: 0.000349MYSTT/min   2.000000MYSTT/GB |
```

Maybe the issue was not in web-ui but with actual file permissions? Because the config.toml file is created with 644 permissions and mysterium-node user as the owner:
```
root@myst:~# ls -l /etc/mysterium-node/
total 20
-rw-r--r-- 1 mysterium-node mysterium-node  333 Dec 16 12:11 config.toml
...
```

**Comment by chompomonim** [comment]
I will create new machine and install myst there today.

**Comment by chompomonim** [comment]
Can't reproduce anymore. Closing issue for now.
