### ISSUE TITLE
0.41 ARM64 Unavailable Dependency

### ISSUE THREAD

**Issue by joesixpack** [mysteriumnetwork/node#3040]
0.41 from the repository suddenly stopped working and I attempted a manual install:

```
sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"

...

Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 myst : Depends: libc6 (>= 2.32) but 2.31-0ubuntu9.1 is to be installed
E: Unable to correct problems, you have held broken packages.

```
2.32 is not availabe in Groovy or Hirsute under arm64.

**Comment by tomasmik** [comment]
Hi there, any chance you could provide additional information on this? I was able to install Groovy on my arm64 machine running ubuntu and I can find the libc6 package in the correct version:
```
myst@ubuntu:~$ apt-cache policy libc6
libc6:
  Installed: 2.32-0ubuntu3
  Candidate: 2.32-0ubuntu3
....
```

I've tried installing `node` and it seems to install and work. Could you maybe try out our [PPA](https://launchpad.net/~mysteriumnetwork/+archive/ubuntu/node) instead of the install script? Just make sure you remove any node links from cat /etc/apt/sources.list or other places pointing to it.

Most probably cause of this error: `Depends: libc6 (>= 2.32) but 2.31-0ubuntu9.1 is to be installed` would be if you tried to install our Groovy built package on Hirsute.

**Comment by tomasmik** [comment]
Im closing this issue for now. If above information won't help, feel free to re-open it.
