### ISSUE TITLE
Investigate why WebUI and MMN shows different stats

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3133]
WebUI and MMN dashboards shows different session counts and earnings. We should investigate why that difference appears.

**Comment by chompomonim** [comment]
Was any progress on this task done?

**Comment by ignasbernotas** [comment]
Few things that might explain the differences between MMN and Node UI balances.

Node bounty eligibility requirements for both leaderboards:
- Node has to have a wallet set
- Node has to be up to date
- Node cannot share the same IP or subnet as other nodes
- Node cannot be marked as malicious to receive a payment

Additional residential bounty requirements:
- Node's IP has to be residential
- Node's IP has to belong to one of the supported bounty program countries

Reasons why the earnings can mismatch:

1. MMN aggregates and stores monthly records. Its API returns data for the current month only. I'm not sure what the time range for the reports is set in Node UI, but this may be something to look at.
2. Prometheus metrics aren't always up to date (as you can see in https://github.com/mysteriumnetwork/my.mysterium.network/issues/58). Prom metrics may be stale, outdated, or cached. This means that MMN will display incorrect balances.
3. MMN accumulates monthly balances. 
3.1. E.g. a node earns 10 MYST in Jan but was not paid for eligible reasons (other nodes outperform this node and it does not fit into the leaderboard, or it earned not enough tokens for us to make a tx), those 10 MYST are transferred to the next month.
3.2. **If MMN shows a smaller balance than Node UI**. E.g. a node earns 20 MYST in Jan, but was not eligible for various reasons, those 20 MYST will not get transferred to the next month. If the node earns 10 MYST in Feb, MMN will show 10 instead of 30 like the Node UI, because only 10 MYST out of the total 30 are eligible for the payment.
3.3. MMN balances also depend on the bounty payment date. Until the bounty payments are executed and the bounty payout script (@interro handles this) calls MMN's API to update the nodes with payment records (tx id, amount, etc), the balances are still accumulated with the unpaid month. Once the payments go through and MMN gets updated, the balances are shown for the current month only (unless a node was not paid, then the balance continues to accumulate).

Session counts, data transfers, and availability metrics:
Until MMN can directly pull node metrics (not from Prometheus), there will always be a chance that the numbers are inaccurate. I don't know a way around it.

I think the best way to solve this issue is to improve Node UI UX with explanations as to why the numbers mismatch. Because of these external factors mentioned above, I'm not sure what else can be done. These are 2 separate systems that use separate data sources, until this can be unified, I don't think it's possible to improve its accuracy.

@chompomonim @eugenegoncharuk 

Hope this helps ✌️

**Comment by chompomonim** [comment]
@eugenegoncharuk is this already solved?
