### ISSUE TITLE
Payout (beneficiary) address should be visible after registration

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3136]

**Comment by tomasmik** [comment]
Address is saved and can be checked after registration.
UI shows `N/A` until at least a single promise is settled, because it received and displays that information using an `sse` endpoint.

This can be fixed by requesting tequila to beneficiary address explicitly using `/identities/:ID/beneficiary`

**Comment by etherunit** [comment]
Beneficiary (payout address) autoswitched to 0x0000000000000000000000000000000000000000 in UI. No changes have been done there.
<img width="519" alt="Screenshot 2021-02-25 at 13 38 53" src="https://user-images.githubusercontent.com/60128746/109148591-21f96600-776f-11eb-9917-d2f2695d79ff.png">

Nodes: 0xacf3ac00ccf0a4f14670501b8acfa4f8ea49378a, 0x0286756508c3ee5c516a3f6c27f95341d52f8a65
