### ISSUE TITLE
[windows, bug] can't register node: registration error

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3140]
User can't register node, gets "registration error" without further explanation.
App restart doesn't help either (i.e. repeated registration attempts doesn't help).

Need to find out what causes registration failure.
Perhaps relevant that user is in Iran.

Node: 0.42.1
OS: Windows.

Logs:
[mysterium-node 14.log](https://github.com/mysteriumnetwork/node/files/6028689/mysterium-node.14.log)

Related to: https://github.com/mysteriumnetwork/node/issues/3137

**Comment by vkuznecovas** [comment]
As I said earlier:

The status is reported correctly as RegistrationError.

2021-02-23T13:45:20.431 DBG source/eventbus/event_bus.go:81          > Published topic="registration_event_topic" event={ID:{Address:0x5e8994a6ac990de01360812983efab38b4e7c8f0} Status:InProgress ChainID:5}
...
2021-02-23T13:45:49.962 ERR source/identity/registry/registry_contract.go:256 > Subscription error error="read tcp 10.7.2.2:50581->54.90.76.2:443: wsarecv: An established connection was aborted by the software in your host machine."
2021-02-23T13:45:49.963 DBG source/eventbus/event_bus.go:81          > Published topic="registration_event_topic" event={ID:{Address:0x5e8994a6ac990de01360812983efab38b4e7c8f0} Status:RegistrationError ChainID:5}
At this point in time node is unable to assert the registration status, therefore the connection attempt fails.

It seems that your app is not handling the registration error status or handling it incorrectly. It's up to the user to handle the registration_event_topic events.

You're already handling the events in your apps as otherwise, you'd not be able to notice when the registration is complete. You need to handle the registration error the same way you handle the other registration statuses. I do not have access to your app's source code so I can't help you with that.

There's at least 3 things you can do to resolve this:

1) Try to register again, this triggers a sequence in node that will try to refresh the registration status.
2) Try to get the registration status from node as this once again triggers the same sequence of events.
3) Restart node.

This will not be handled by node as there are many ways you might want to handle this in the end app and it is up to the user to do so.

**Comment by cvl** [comment]
Viktorai, please don't close unresolved issues. It just takes time for me and everyone else to reopen and remanage issues.

I'm reporting the bug, that node can't register identity as registration error occurs. You're telling me, that the fact, that registration error occurs, is normal and I shouldn't worry.

This is not acceptable, as the app without identity registration is non-functional.

Please try to look up why registration failure occurs. You should see the error in the backend, as there's no error besides "registration error" in the consumer node.

This is not an app issues, as other users don't get this error, and there's nothing specific to handle this registration error.
As mentioned, multiple attempts to register identity doesn't help.
There must be some issue either in the back-end, or Iran firewall or whatever.

Please investigate. If you'd say "I don't know" - this answer is perfectly acceptable as well. Just be frank and honest.

**Comment by vkuznecovas** [comment]
I've already added the error, it's a network error due to firewalls in Iran.

**Comment by vkuznecovas** [comment]
There are countries in the world with firewalls, it's going to be a cat and mouse game, therefore your app should be handling the failure cases of the node, which is just the case here :)

**Comment by vkuznecovas** [comment]
Just to add more context - the only thing we could do here is force a retry, which would then result in the same issue where we'd still be forced to return the RegistrationError. It is up to you to decide what to do in such cases. 

The node client(the CLI) will just inform the user, why can't you do the same?

**Comment by cvl** [comment]
Now we're getting somewhere, thanks :)

Would you suggest to attempt multiple times, or use some different IP/domain to communicate to Mysterium registration services?

As there's no such behavior in MysteriumVPN (my app is a simple fork), it would help me to understand how I should handle this to work around those firewalls.
Some p2p connection in some country could help I guess, e.g. consumer node could attempt to connect to residential node in Iran friendly country, this residential node would work as a gateway to registration service.

**Comment by cvl** [comment]
Well, I'm doing the same, but this doesn't keep the customer, as it doesn't work :)
Now I can tell that it's blocked in Iran (because that's what the customer asked in the first place - does it work in Iran) :)

**Comment by vkuznecovas** [comment]
We've built in the workarounds in the node itself: if lookup via DNS fails we fall back to IPS. There are no extra workarounds in the apps. 

What I would do in this case - probably try again and if it crashes again just inform the user. There's literally not much we can do at that point. Bypassing firewalls is very specific to the firewall and would have to be thoroughly investigated. 

It's something we'll work on in the future but for now, the focus is elsewhere.

**Comment by alexandre-leng** [comment]
Still have this issue
