### ISSUE TITLE
Kill switch for Android

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3168]

**Comment by cvl** [comment]
Why was this closed?

**Comment by chompomonim** [comment]
I think because this is done?

**Comment by chompomonim** [comment]
@soffokl could you confirm that kill switch is done and was introduced into android in this PR?
https://github.com/mysteriumnetwork/mysterium-vpn-mobile/commit/1e0d27633b8e469de8aee1e93b95828a23d4ff37

Could you write short explanation how it works and how to enable/disable (e.g. in settings) and test it?

**Comment by soffokl** [comment]
It's required to set flag to enable it for now, since it's disabled by default:
`config.Current.SetDefault(config.FlagKeepConnectedOnFail.Name, true)`
https://github.com/mysteriumnetwork/node/pull/3248/files#diff-586acf11d35eb5e5dcd0f88f3356a0238827631b64093754d5ad359babdc9fd1R152

If this flag enabled, a connection will not be disconnected on errors and will be kept forever even if the provider stopped to respond. Only consumers can explicitly click the disconnect button to stop it. 
All traffic keeps going through the tunnel, and not leaking directly.

**Comment by cvl** [comment]
@soffokl 

I can see that Android lib and mysterium-vpn-js has setDisableKillSwitch amongst connect options.
It feels like kill switch should be enabled by default (unless I set "disable kill switch" to true).
Is this something I should use?

As per your suggested implementation for Android:
- Where is this config? I can't find it anywhere in Mysterium app, not in MobileNodeOptions (looked at 0.45.0).
- How should I implement this in desktop app?
- Is this a real kill-switch (i.e. can I market is a kill-switch) - as it sounds like it's a reconnect feature. In other words: if connection is dropped for any reason (node, wifi signal lost/reconnected whatever), would the traffic leak, or will the internet be disabled until user manually clicks Disconnect, or node reconnects to provider successfully?
- What's the difference between setDisableKillSwitch? Would those two implementations conflict?

**Comment by cvl** [comment]
Also:
- how would you suggest to test this (the easiest way if possible :) )?
- is it possible to get a notification (e.g. status change or smth like that) once the connection is dropped, so I can notify user that something bad happened and he should Disconnect and Connect again.

**Comment by chompomonim** [comment]
@soffokl could you cover questions asked above?

**Comment by cvl** [comment]
Possible to get some light on this?
Time spent developing the (critical) feature, but it's not used in any app.
