### ISSUE TITLE
Export private keys

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3192]
Node should have functionality to encrypt private keys with given password and would expose file with encrypted keys.

- [x] Bindings for android to export private keys
- [x] Tequila endpoint which accepts password, encrypt keys and allow to download them (in a secure way) --> will be used later in nodeUI and CLI ( https://github.com/mysteriumnetwork/node/pull/3198 )
- [x] CLI should allow to download private keys encrypted with given password https://github.com/mysteriumnetwork/node/pull/3215

**Comment by tomasmik** [comment]
Exporting privates keys using tequila creates this sort of a security issue. Right now to get access to a key for example on linux running node, you have to have `sudo` permissions. If we add this as a tequila endpoint, anyone can query and export keys.

Problem is that we do not have any passphrases on the keys, which makes it easy to just steal the key and use it. We can't really add passphrases because of how the apps/node work.

My proposed solution is this:
* Mobile: Add bindings and use them to export the key using the `mover` introduced in #3198 . Though we should also ask for some kind of password probably? I guess we dont have one there?
* CLI/Linux: Use the `mover` together with sudo password to export the key
* Desktop apps: Just show the path to the keys and tell the user to copy them out? as we dont really have direct access to node in desktop. ( this is really not a user friendly solution)

We could consider adding the tequila endpoints to export the identity if we had some form of security for these endpoints, like a one time password MMN could issue, or a general password user creates when launching the application/node.

Second part of this - import (https://github.com/mysteriumnetwork/node/issues/3193), could be done easily through tequila as importing keys probably has no security problems.
@chompomonim  ideas?

**Comment by chompomonim** [comment]
> Mobile: Add bindings and use them to export the key using the mover introduced in #3198 . Though we should also ask for some kind of password probably? I guess we dont have one there?

**Comment by tomasmik** [comment]
The biggest issue here is probably the desktop apps. Copying files from directories is just not user friendly. Do you have any ideas? Or we just skip it for now and provide this feature only for cli (which probably is only useful for providers)
