### ISSUE TITLE
[bug] Provider's web preferences leaking to consumers?

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3237]
**Describe the bug**
Connected to Germany node 0x3d2a73bb408d0a5ace3e8fd71ded43cf6e344cfc
I'm seeing google in arabic and in reverse.

Scary.

<img width="1095" alt="Screenshot 2021-03-23 at 11 26 19" src="https://user-images.githubusercontent.com/100252/112126193-e070a500-8bcc-11eb-9d2c-e9c73b3d84cf.png">

IP location:
<img width="1065" alt="Screenshot 2021-03-23 at 11 28 02" src="https://user-images.githubusercontent.com/100252/112126288-f7af9280-8bcc-11eb-8e0a-67793f5efd82.png">

**Environment (please complete the following information):**
 - Node version: 0.45.0-rc4
 - OS: Windows

**Comment by vkuznecovas** [comment]
This is how google handles fingerprinting on their side and has nothing to do with our application. Causes could be numerous, for instance be it a shared wifi in a dormitory or similar situations.

**Comment by cvl** [comment]
It has a lot to do this Mysterium application, because that's what users will experience.

Any ideas how this can be resolved?
I can see few options so far:
- Communicate to providers, that they should fix such issues (could be some instructions etc how to do this).
- Test (e.g. by crawling google and the like) & ban such providers (could be same grace period with notification to provider)
- Change this fingerprint somehow?

Anyhow, if user will see such UI he'll get scared and tell others. Reputation will go quickly to 0.

**Comment by vkuznecovas** [comment]
What we could do is ask Google to honor HTTP headers. They haven't been doing that for years and many have tried and all have failed.

`Communicate to providers, that they should fix such issues (could be some instructions etc how to do this).` - is the provider using an Arabic version of Google because he speaks Arabian an "issue"? It seems like you're suggesting profiling based on the provider race.

`Test (e.g. by crawling google and the like) & ban such providers (could be same grace period with notification to provider)` - we're definitely not going to be banning people due to their spoken language.

**Comment by cvl** [comment]
Arabic is not a race. Let's not start with this.

I'm suggesting to provide quality service: if user connects to Germany, he should expect either English, or in German. It doesn't relate to race, gender, sexuality.

Thanks for the answers.
