### ISSUE TITLE
Can't access geo-restricted content

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3262]
**Describe the bug**
Can't watch the videos at http://amwager.com/ while on VPN.
The content is geo restricted (US).

**To Reproduce**
1. Connect to US node, register account at http://amwager.com/ between 3:00 AM PST - 12:00 AM PST.
2. Find any race which is ongoing, click green button "Video".
3. Video player will say that there was an error. See the screenshot:
<img width="1843" alt="Screenshot 2021-04-01 at 20 36 32" src="https://user-images.githubusercontent.com/100252/113333482-28a96900-932b-11eb-84bd-b4489825d6e2.png">

**Environment (please complete the following information):**
 - Node version: 0.44.0
 - OS: MacOS, Windows

**Comment by Snawoot** [comment]
I've reproduced this issue on residential IP in US.

Here we can see response body of failed request:

![Screenshot_win10-clean_2021-07-27_14:15:15](https://user-images.githubusercontent.com/3524671/127190479-bf24b2e8-3724-4dee-8487-75c168a1faf0.png)

It states: "User role not authorized for this action".

On my screenshot and screenshot in original issue message we can see "Enable Wagering" button which prompts user to enter his personal details and credit card number for validation. Also such prompt pops up right after registration on site. My guess was: user is just not allowed to view video because they didn't cleared their identification.

In order to check it I sent inquiry to AmWagger support service:

![image](https://user-images.githubusercontent.com/3524671/127191380-ffad70cf-94f8-4ea1-a784-dfeed01f334b.png)

We have two takes from this:

* It's not required to wait for particular time window when live translations are online to reproduce this issue. It's also possible to check with archive videos.
* We can't confirm user was denied because something is wrong with residential IP, VPN or software.
