### ISSUE TITLE
No error when identity registration fails

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3444]
**Describe the bug**
Identity registration fails (apparently due to go-erli ddos attacks), yet the api doesn't throw any error when registering failed. Simply I get unregistered identity when trying to check registration status.

No logs produced.

**Expected behavior**
API should throw an error in case registration fails.

**Environment (please complete the following information):**
 - Node version: 0.46.1
 - OS: MacOS

**Comment by tomasmik** [comment]
This was solved for now with a hack. All identities are registered (even though node can still report as being in progress on the registration). It will automatically be solved with the new network release.

The API isn't throwing any errors and probably will never throw any errors because of how it works. Registration takes time, usually can't respond with anything block chain transaction related as a response from the API unless it's some premature failure.

Node does check if the registration is successful itself and should resend a request to re-register it just didn't do fast enough because of how slow everything was in goerli.
