### ISSUE TITLE
Testnet3: NodeUI sets no stake when registering

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#3602]
![image](https://user-images.githubusercontent.com/40318863/124910377-33436080-dff4-11eb-946c-33a6d6af44dd.png)

This actually makes me a consumer after registration

**Comment by mdomasevicius** [comment]
I will set 10 MYST as agreed  
@chompomonim we discussed 0 stake here and payment team disagrees

**Comment by chompomonim** [comment]
I think we should make some additional changes in transactor and in node on process how we're going to open payment channels. 

1. Now we have separate function for opening payment channel `function openConsumerChannel(address _hermesId, uint256 _transactorFee, bytes memory _signature)` or even one without fee `function openConsumerChannel(address _identity, address _hermesId)`. Beneficiary will be set to payment channel address, exactly what we need.
2. Technically Hermes channel is always opened.  during first settlement, so technically we don't need to open it during registration.
3. `registerIdentity(...)` should be called only if node decides to have big stake. But because we don't force then to have stake, practically this should be never used. But if we don't want to use `openConsumerChannel(...)` at this stage, then we still can use `registerIdentity(...)` by passing zeros into `beneficiary` and `stakeAmount` fields.
