### ISSUE TITLE
not connecting to node and no signal in quality column

### ISSUE THREAD

**Issue by untitledlt** [mysteriumnetwork/node#3739]
when I am trying to connect to the node through mobile app it is not connecting to it and in quality column their is no signal as well. Why is it so? Please check this issue and let me know if I need to perform any steps to resolve it.

Thanks,
Sohail

_Originally posted by @sohailshaikh333 in https://github.com/mysteriumnetwork/node/issues/3714#issuecomment-892595237_

**Comment by sohailshaikh333** [comment]
Hi Team,
Any updates on this?

Thanks,
Sohail

**Comment by sohailshaikh333** [comment]
Hello team,
Today when I clicked on check connection it's saying No active services found. Please help to resolve this issues it's been a long time this issue is stretched.

Thanks,
Sohail

**Comment by sohailshaikh333** [comment]
Hi Team,
Today the check connection is working fine I am getting the message "Wireguard connection queued" so that issues seemed to be resolved but the main issue is still their the node connection issue and the network quality says it has no network, that issue is still their. Please help to resolve it.

Thanks,
Sohail

**Comment by sohailshaikh333** [comment]
Hello team
Any updates on this issue?

Thanks,
Sohail

**Comment by isaackielma** [comment]
Could you please give us your node ID?

**Comment by sohailshaikh333** [comment]
Node ID: 0x08844b21ce937c464ab9a96d26ffc4ce940f1afe
