### ISSUE TITLE
[windows, bug] can't access LAN when connected after migrating to 0.53.1

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3792]
**Describe the bug**
Upgraded to node 0.53.1
LAN doesn't work anymore after connecting...

Huge downgrade, must be fixed asap.

**Environment (please complete the following information):**
 - Node version: 0.53.1
 - OS: Windows

**Comment by tomasmik** [comment]
Please use the provided bug template to describe the issue. As for now there is no way to debug this on our end. We dont even know from what version you've upgraded. As long as I'm concerned there were no changes made in that version that would affect this.

**Comment by cvl** [comment]
@tomasmik I'm using the template. What exactly do you need that's not provided?

Please do not close unresolved issues.

**Comment by tomasmik** [comment]
The biggest problem with this is that it's missing:
```
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

Version  0.53.1 has nothing to do with LAN or any other networking changes. It just made a small change to filters. From what version did you upgrade to what, does it happen on other machines, etc.

**Comment by cvl** [comment]
Huh.

We are not children.

Go to app, open app, click connect.
See LAN not working anymore.

What does this change besides the fact that we've just wasted 5 minutes each?


0.53.1 fixed DNS leaks, see https://github.com/mysteriumnetwork/node/issues/3462#issuecomment-896978490
It's not just some small changes.

**Comment by tomasmik** [comment]
@Snawoot Please take a look if you can repeat the bug here as it seems fine for me.

**Comment by cvl** [comment]
Thanks.

@Snawoot in my particular case, I'm connecting to Windows 10 machine from Mac machine using Microsoft Remote Desktop. When I connect to node on Windows machine, connection is lost, and I can't access it anymore.

**Comment by Snawoot** [comment]
Hello!

It's not completely fine, but it's an expected state for this iteration of development.

At this moment we suppress all communications with WFP on Windows except ones via VPN in order to ensure that:

* There is no DNS leaks.
* No IPv6 leaks.
* No rogue ICMP redirect messages from local network casting connections out of tunnel.
* DHCP server is not coercing machine to local proxy with PAC script option to hook on it's traffic even with VPN active.

Exactly same methods are used by [wireguard-windows implementation](https://git.zx2c4.com/wireguard-windows/tree/tunnel/firewall/rules.go?h=v0.4.2), which we consider as a reference secure VPN client.

Maybe there should be setting to whitelist some LAN networks or something like this, but it should be kind of expert option and definitely was out of scope for initial security fixes.

As for your case with RDP connection (which is clearly not a common usage scenario), I see following options, assuming it's a test bed:

* Use virtualization and connect to VM console remotely. This way there will be no interference between control channel and testing of network applications. Modern hypervisors do not cause overhead and have snapshots (convenient for clean test, rollback to snapshot and have clean install). Personally I work this way, I run Win10 inside kernel-based VM on Linux.
* Create allowing rule for RDP traffic in Windows Firewall with high priority and final option (so no other rules will be applied for packets matched to this rule). It'll override WFP rules created by `node` instance on Windows. Can't give specific instructions on that, however, but I'm pretty sure that's possible since we do essentially same.
* Just use something like [TeamViewer](https://www.teamviewer.com/en/) which connects/reconnects via Internet.

**Comment by cvl** [comment]
Can I create a "feature request" to enable LAN when on VPN (same as all other VPN clients I've tried so far), or is this never gonna happen with Wireguard?

btw, LAN works on Mac, so it's only Windows problem.

**Comment by cvl** [comment]
p.s. thank you for sophisticated answer!

**Comment by Snawoot** [comment]
> btw, LAN works on Mac, so it's only Windows problem.

Yep, WFP is literally Windows Filtering Platform. Also Mac doesn't do stupid things with DNS trying every DNS it remembers like Windows, so there is no need to secure it this way. However, it'll be fine if someone will test if there DNS and IPv6 leaks on Mac.

> Can I create a "feature request" to enable LAN when on VPN (same as all other VPN clients I've tried so far), or is this never gonna happen with Wireguard?

Sure, create issue and this way we'll see later how it is demanded.

Have a nice day!

**Comment by alimbada** [comment]
You need to allow split tunneling with exceptions for common LAN addresses. This is how Cloudflare's Warp client works on iOS. It's unacceptable that I RDP into another machine where I want to use Mysterium and then I get disconnected from it as soon as the client connects to the VPN. This was not the behaviour in previous versions and needs to be fixed.
