### ISSUE TITLE
[feature request] Account Management

### ISSUE THREAD

**Issue by JPeetz** [mysteriumnetwork/node#3942]
Hello Mysterium Team,

I'd like to bring forward an idea for Account Management.
Would it be possible to "couple" the account from the App on your devices with the account running a Node?
This way you enable users to spend the token they've earned; instead of complicated "buy here and transfer there".
Direct purchase of the token, via PayPal i.e., would also make the usage of the App and your dVPN much easier.
In the background you could link it to an exchange to proceed with the purchase.

Just some ideas to make the service more user friendly.

Cheers, Joerg

**Comment by tomasmik** [comment]
> Would it be possible to "couple" the account from the App on your devices with the account running a Node?
This way you enable users to spend the token they've earned; instead of complicated "buy here and transfer there".

I think that is covered by https://github.com/mysteriumnetwork/node/issues/3455. Unless I am misunderstanding something. In theory it should be possible now too but rather tricky forcing you to disable providing the service or to transfer funds from provider account to consumer in order to use those funds.

> Direct purchase of the token, via PayPal i.e., would also make the usage of the App and your dVPN much easier.
In the background you could link it to an exchange to proceed with the purchase.

Something similar is already in the works and should be available in mainnet.

**Comment by JPeetz** [comment]
Hello Tomas,

Thanks for looking into this indeed.
If it would be possible to "link" the consumer app with the provider API
key, at least the consumer app could refer to the provider wallet address.
...if you understand what I mean.

Cheers, Joerg
