### ISSUE TITLE
MMN Dashboard NOT displaying the list of nodes

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4084]
**Describe the bug**

MMN Dashboard NOT displaying the list of nodes, or randomly switching from displaying the list, to this "Setup your first node" page is kind of annoying.

When I overlay "Nodes" I see the full list, but it is truncated because I have many nodes and this smaller list is size-limited by the vertical size of the webpage.

Node ID: 0xd1a45106c9d05b356ae875dbdc68ec2b890a4493

**To Reproduce**
1. Go to 'MMN Dashboard'
2. Click on 'Login'
3. Scroll down to 'see nodes'

**Expected behavior**
Node list should automatically display.

**Screenshots**
![image](https://user-images.githubusercontent.com/84313603/137290334-28cfefa2-7d6a-4d34-a675-cc64adf38e7b.jpeg)

**Environment (please complete the following information):**

OS:
Alpine Linux v3.12(docker)
Architecture:
linux(docker)/amd64
Node version:
0.67.0

**Additional context**

54 nodes in total

**Comment by CharlyEmpereurmot** [comment]
Hi, Isaac had opened this issue for me. It looks to me this is indeed the same as #4045.

**Comment by CharlyEmpereurmot** [comment]
Also, I kind of disagree that this is low priority because without this complete page that displays node statuses, it is impossible to get an overview of which nodes are running OK and which ones need to be checked for maintenance. To this end, the only way to check all nodes is to go to the "Global leaderboard" page, which has enough vertical size to display the full list of nodes when overlaying "Nodes" button in the header menu, and then click nodes one by one.

**Comment by Donatas-MN** [comment]
https://github.com/mysteriumnetwork/node/issues/4045 is now in progress and we should have a fix shortly. I will update on release.

@CharlyEmpereurmot Regarding priority classification, it's internal categorisation, but it definitely does not mean that issues with "low" priority won't get fixed. It's more about putting them to correct buckets on our lists.
