### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by ayilaraolamilekan** [mysteriumnetwork/node#4127]
No doubt the VPN is fast and very good, but the problem I have encountered so far is

1. Connection problem: most of the saver uploaded on the VPN are not connecting, only few of these savers are working others wouldn't connect.

2. On Hold: few of the savers that connects end up working for few minutes and shows "on hold" once this is shown all internet activity stopped working.

My suggestion:

I will suggest will have little savers that are connecting and working perfectly without going on Hold after few minutes of usage, it's very much ok and perfect to have few savers uploaded, working and doesn't go on Hold than having plenty of savers that would not connect, it's makes selection of working savers more difficult to spot when we have hundreds of savers that is not working, it's annoying trying 10-20 savers without getting one that will connect and when you finally get your hand on the one that connects and works perfectly the next thing is for it to go on hold after few minutes of usage this is pretty bad. Please improve on your savers.

1. Reduce the savers to minimum of quality and working savers.
2. Work on savers going on hold after few minutes of connection. 

Thanks

**Comment by chompomonim** [comment]
Connecting issue may be caused by many factors. Your ISP, country, connection type, node ISP or configuration... The node is not working for you may be working for 95% of other users. Reducing servers doesn't make difference, because part of them are ok of one set of users, another part is good for other users.

We constantly are looking into different ways how to increase connectivity rate and filter out nodes for particular consumer which has less probability to be connectable. 

We'd like to debug your on hold issues, this shouldn't be happening like that. Could you provide your logs so we could have chance of debugging this issue?
