### ISSUE TITLE
Errors and missing MYST after withdrawing >100 MYST at a time

### ISSUE THREAD

**Issue by oldsweatyman** [mysteriumnetwork/node#4559]
First withdrawal was a little over 400 MYST for which I received 99.9x MYST twice. 

Transaction ID: https://polygonscan.com/tx/0xb75e90e59f64face6d4aa8d40dcf77b260e4aa8edf1a156af56bde4b71f100fc

Second withdrawal was for ~160 MYST for which I again received 99.x MYST but only once.

Transaction ID: https://polygonscan.com/tx/0x84979410a6679d06b8e36390d3448ca3fb5750f63886733bebb972d71d5214e2

Third withdrawal I do not recall the intended withdrawal and I hadn't noticed the discrepancy, it was 15 days ago

Transaction ID: https://polygonscan.com/tx/0x853157238228ea8b48f9bd33531a336883eada3fa102f1f81c0b660607ce119d

Not sure if this is related but I've earned MYST since yesterday and my wallet shows "< 0.0000001 MYST " for the balance.

Node ID: 0x3a66e8144a55898d989e11dced63f1c9c49b4d6b
Payment Channel: 0xB5b04de044fEFDd5C5c689A8ccDe9AD1fa9B2d24
Withdrawal Address: 0x78c4cc754f3d69406eba1d78b83a5dd860ee2953

Please let me know if there's any other information I can provide. On mainnet I have earned "1300" MYST and have received ~500 from my withdrawals as you should be able to see on my node and wallet information. Another extra piece of info is that mystnodes.com says I have earned 1286.356 MYST but my web UI says 1300 flat.

**Comment by MatysLdn** [comment]
Hello. 
I had almost the same issue.

Was trying to withdraw over 200MYST and on Node UI had info that it was successful but no transactions on the crypto chain have gone throughout. Then I had errors asking me to try again for a few days.

Then I've noticed my balance of MYST has gone down like I withdrew some of MYST but obviously, none of MYST have arrived in my wallet on the polygon. Anyway...

Now. I tried again to withdraw over 180MYST that's withdrawal request **transaction ID:**

https://polygonscan.com/tx/0x17d64e06029b2e9177edc7dc1f64a33526d3370bfd378922e7b734df6c232ae1

Instead of 184 MYST I received 99.99 MYST which you can see there, **transaction ID:**

https://polygonscan.com/tx/0xd03e0cdc650444ae0f50151ac1316f47e0e0a0581d37d08312cfcb36e85fb42d

While my total earnings on MYST website is showing 293.583368 MYST I have only received 99.99 MYST
Then my balance on node UI was showing < 0.0000001 MYST - my understanding is that system believed that I have withdrawn all my MYST ??

Node ID:  0x776f68e6dbd4800308ae9be8580a623070d3451f
Payment Channel: 0x759Fb8c85D0DdB2e5F599d1861e18478236c48bf
Withdrawal Address: 0x6cf071617b30040652becbfb304306a85ac3f6b7

For me, it looks like there is a bug that happens when withdrawing more than 100 MYST ? And regardless of the amount of withdrawal, it sent only 99.99 MYST ??

I've lost a bit of profit there. I'm not too sure if you can rectify this? But for me, it is more important to help you sort this out so this won't happen again to me or anyone else. Thanks!

**Comment by MatysLdn** [comment]
Hi.

Would be great if we were aware of this so ppl could prevent this issue to happen.
I've tried to withdraw as you suggested but still didn't receive the right amount.

I wonder if this is because once I was trying to withdraw over 200 MYST which is double of 99 and therefore got only top-up to 99 MYST on the next withdrawal but not on following? eg: I'm withdrawing 230 MYST so I will receive 99MYST once, then 99MYST second but 30MYST will be missing??

This is my withdrawal history:
![image](https://user-images.githubusercontent.com/54354015/149562158-cd34a9a1-7510-4775-bb29-bbfee55f1678.png)

And that's my total earnings:
![image](https://user-images.githubusercontent.com/54354015/149562965-548d18aa-8478-4693-b9c6-38fc1fcfbc0a.png)



You see the total earning is showing 360 MYST but the total of my withdrawals is approx 242MYST
The last three withdrawals from 7,23,15 MYST are accurate and exactly as were shown on node UI but nothing to compensate for missing withdrawals over 100 MYST.

Again, I'm not complaining here. I'm happy to help this project grow and I know you will rectify this issue!
Good luck!

**Comment by Donatas-MN** [comment]
Total earnings represent earnings before all applicable fees (20% + blockchain fees), so I would say amounts looks about right (360 total vs 240 withdrawn). Moving forward this ratio will be better as we increased auto-settlement threshold. 

I understand that this issue is frustrating, but this limit is indirectly affecting withdrawals, so we didn't know this in advance. Newest node version (coming out tonight most probably) will limit withdrawals to 99 MYST per transaction, so it should be fine moving forward. 

Once again, sorry for the inconvenience. We appreciate your help and support for the project!

**Comment by Donatas-MN** [comment]
1.1.9 update introduces 99 MYST withdrawal limit.

**Comment by MatysLdn** [comment]
Thanks for the explanations!

I'm lucky enough to be quite long with the project and been paid in ETH when it was worth $100, so I won't be crying here :D

I know this is a different matter but maybe devs could consider "update" button on NODE UI ?

Thanks !

**Comment by oldsweatyman** [comment]
Are there any updates on retrieval of the lost tokens for those who withdrew >100? I'm not sure on the math for mine but it is in the hundreds of MYST.

**Comment by oldsweatyman** [comment]
Can confirm that repeat withdrawals of any amount (such as 0.25 myst) are including blocks of 99 MYST presumably from previously 'lost' MYST with transactions that were over >100 MYST. Relief! Thank you for the work.

**Comment by Donatas-MN** [comment]
@oldsweatyman Thanks for the confirmation! Yes, it should allow to get all missing MYST by doing small withdrawals.

@MatysLdn we will check regarding Update button.
