### ISSUE TITLE
Changing API on existing node do not work

### ISSUE THREAD

**Issue by Jhobean** [mysteriumnetwork/node#4693]
**Describe the bug**
I use an existing node and change the API number on the UI. When I go on https://mystnodes.com/nodes, I'm not able to see my node.. Node running and working. I try claiming the node on the network and it's the same problem.

**To Reproduce**
1. Change API key on the UI
2. Go on wesite and dont see your node. You can see it only on the old API website

**Expected behavior**
Node should transfert

**Environment (please complete the following information):**
 - Node version 1.2.2
 - OS: Ubuntu
 - Your identity : 0x32ff1c5921a85fdff156becb0e89646943817b60

**Additional context**
Node Was on Docker before. When I change it to ubuntu, it's the moment I try change the API key

**Comment by veldspar** [comment]
try the following: backup your identity: 
- stop mysterium-node service
- backup directory /var/lib/mysterium-node 
- delete /etc/mysterium-node/*
- delete /var/lib/mysterium-node
- create new /var/lib/mysterium-node
- change ownership of /var/lib/mysterium-node to mysterium-node (`chown -R mysterium-node:mysterium-node /var/lib/mysterium-node`
- start mysterium-node again. You will be led to the onboarding process(since a new identity is created)

I had the same issue today, apparently just deleting the api token from config files is not enough, as of now it seems like theres a bug that only allows api token to be set during onboarding.
I wrote a little script to automate the process of changing your identity to a new one:

`#!/bin/sh
systemctl stop mysterium-node
tar cfz /root/jan22.tgz /var/lib/mysterium-node/
rm -rf /var/lib/mysterium-node/
mkdir /var/lib/mysterium-node
chown -R mysterium-node:mysterium-node /var/lib/mysterium-node/
rm /etc/mysterium-node/config-mainnet.toml 
systemctl start mysterium-node
`

**if you choose not to backup your files make sure to settle all unsettled amounts and withdraw your balance, or else it will be lost**

**Comment by Jhobean** [comment]
Maybe i'm kust poor with cli but now it do not work lol.
I made your line and im always in onboarding....  Bit  I think there a big because you are suppose to be able doing it with UI

**Comment by etherunit** [comment]
@Jhobean As far as I understand, you have created a new mystnodes.com account with a new API key. Now you're trying to claim your old node using a new key (swapping an old one with a new one)? Is that right?

**Comment by Jhobean** [comment]
> @Jhobean As far as I understand, you have created a new mystnodes.com account with a new API key. Now you're trying to claim your old node using a new key (swapping an old one with a new one)? Is that right?

Exactly.

**Comment by etherunit** [comment]
Do you still experience this problem? @Jhobean

**Comment by Jhobean** [comment]
I don't know I unistalled it. I close issue. Thx for asking.
