### ISSUE TITLE
Bug Report + Feature Request Regarding the Mysterium discovery API and how it could be improved

### ISSUE THREAD

**Issue by sarthakgangwar** [mysteriumnetwork/node#4774]
Lack of Balanced and Fair Quality Value through the API makes it hard for Real Good Runners to get traffic while Average and Lucky node runners make the major profits

Steps to reproduce the behavior of api that results in a absurdly high ping:
1. Go to https://discovery.mysterium.network/api/v3/proposals?provider_id=0x4439ccec1773308b3f7953edbe04d8241c722732
Sidenote : the following node is from "Adine" a mod in myst discord channel

The API should always report a fair quality , latency and bandwidth value . Instead the current API highly depends upon the old sessions to calculate the following values that make it very unreliable as instead of The sole node the values now are Dependent on the Client's Internet Speed And Latency also. Due to this many times many good nodes like mine and adine's receive a very bad quality which in turn directly reduces the revenue from running a node.

Even though my node is running on a 500mbps download and 800up fiber optic connection the rating i got is 1500latency and a mere 2 mbps of bandwidth . both of them i feel was a issue with the client that connected to my node . If i run a speedtest to anywhere in the world (i am from india) the max ping that i see is 150-175 ... and minimum speed of 100mbps at the farthest locations.

as a way to fix this we could upgrade the api to use the speedtest site to regularly (around every 12 hours) run a speedtest to 5 most major cities all around the planet (like Paris , Washington DC , Brazil? , New Delhi , etc) then average it and make a specific quality afterwards . this maintains a consistency of the "quality" and makes the app a lot more fair for the runners by removing the Luck that is currently involved in improving the quality and earnings of the node

**Comment by sarthakgangwar** [comment]
any updates devs ?

**Comment by CharlyEmpereurmot** [comment]
The quality is definitely not estimated in a fair way, indeed. What I noticed is that the test sessions do not seem to allow the evaluation of the Latency, which stays at 0 until a real user session comes in. While Latency is at 0, then the Quality score stays dramatically low, and then users won't connect to the given node because they don't want to use low quality nodes. So here we have a self-sustained loop that disadvantages certain nodes. On the contrary, other nodes will be at an advantage. And the effect will be pretty strong.

=> Biased value for node runners, that's months now!

**Comment by Donatas-MN** [comment]
We're looking into Latency issue, will post an update here.

**Comment by Donatas-MN** [comment]
The reason why you see latency 0 when looking to Discovery link is because this Node did not have connection from you country, so latency could not be measured. For example, this node's https://discovery.mysterium.network/api/v3/proposals?provider_id=0x4439ccec1773308b3f7953edbe04d8241c722732 latency will show as 0 to me, because it did not have connection from Lithuania yet. This country specific measurement is used to make sure latency measurement is accurate as it really depends on how far you're from the node. 

We added a small improvement to Latency measurement, so it should not affect your general quality rating that much anymore until you get more connections (in other words you have real data in more countries). Can you check if quality rating improved for your node?

We will also work on bigger improvements, so this quality measurement is more accurate in different regions of the world for such case when Node did not have many connections yet.

**Comment by sarthakgangwar** [comment]
Thanks for the reply !
The latency is still 0 since as long as i can remember (its 0 for most nodes i check) , Its good to know that it wont affect the quality anymore but.... now its 100% relies on the speed ? is it so ? then it means the situation is worse now since its .. lets say not optimal or accurate .

now since you have disabled latency affecting the quality of node , its even more luck now ... because once again why do our node's speed get calculated by connections . Assume I Have 10gig connection and Consumer has just 10mbps ... my "very great" 10gbps node will be seen as 10mbps one while lets say someone lucky with 1/10 of speed will have higher quality. 

Please make it so that the node runs a speedtest to a Fixed Server so that the "Quality" value remains fair . I Personally recommend once again from main post to have 5-7 prime locations across the globe so that the ping and the speed could be averaged for each node . after averaging it on all we will get a real "quality" which will not at all depend on luck and also maintain a fair distribution of traffic .

I am pretty sure it will help the consumers also .

**Comment by CharlyEmpereurmot** [comment]
Thanks for working on this long-lasting problem.
It appears indeed that the Quality has gone up by a lot on my nodes and it seems this is bringing some traffic already.
6 hours ago all the Latency scores were at 0 and now it looks like there were some user connections that allowed to estimate Latency.

Just a thought: Why not make nodes ping each other within the same country, from time to time, to assess the Latency? Only in the event that no users connected recently and there is a need to re-assess node Quality/Latency. This could also be applied to Bandwidth estimation potentially.

![image](https://user-images.githubusercontent.com/44687951/158717259-9c95064b-0b88-4d62-a9ac-0cf48918b03a.png)

**Comment by sarthakgangwar** [comment]
Well you got lucky ! my node still is very low on quality I have amongst the best connections in India , Located at geocentre ..Basically everything a good node needs . The bandwidth should be 800mbps but rather it shows up as 2.5mbps . So yeah very poor quality rn . 

Speaking of the nodes pinging it's a great idea but might not be possible for speed since every node will have different speed . Last thing we want is 10mbps node speed testing a 1gbps one .

**Comment by sarthakgangwar** [comment]
thanks the overall quality of my node improved . 
the current implementation is more like a temporary fix . I just wanted to ask about your plans over improving "Bandwidth" calculation and if any work is going on right now :)

**Comment by Strasser-Pablo** [comment]
Would a fairer computation not be also based on speedtest on the host computed by the myst app using speedtest cli or some similar library. As with some highspeed fibre setting like 1G or 10G fibre there may not be client using heavy trafic. However the number of clients a host could support could be approximated by the speedtest. For example a host with 1G fibre can support an almost unlimited of browsing client and a good number of netflix user. For latency the ping could be used.

If I understand correctly the current computation is based on average bandwidth utilisation of client so if a lot of light web browsing client connect to you. You end up penalized.

**Comment by Strasser-Pablo** [comment]
To add another example as the OP has. This is the link to the discovery of my node that I managed to put up recently https://discovery.mysterium.network/api/v3/proposals?include_monitoring_failed=true&provider_id=0xa811efb69b3c19dc221f1dfef8991afe82fffb16 . Its indicated bandwitch is very low of 22 MB/s . However, taking a speed test on the node itself not throught the vpn I obtain the following results https://www.speedtest.net/result/c/1467275c-e09c-421b-8ac7-6cc508f4e504 . Which indicate more than 4000 MB/s up and down. I understand that there is some losses due to switching or other reason. But I think giving a way to indicate to consumer the existance of some very fast node is usefull.

**Comment by CharlyEmpereurmot** [comment]
I checked today and I could see pretty high latencies (average ~2k ms) for the nodes I have, that are distributed on the globe. Just a piece of information to help the process :)

![image](https://user-images.githubusercontent.com/44687951/160788200-804ea1a6-aac1-49b5-aa55-db080c88564f.png)

**Comment by Donatas-MN** [comment]
@CharlyEmpereurmot are you still seeing increased latency?

**Comment by CharlyEmpereurmot** [comment]
@Donatas-MN Checking right now with this little script of mine that just requests and filter the discovery API for my nodes, I see these 2 screenshots below, at 1 minute interval. Problem still present, strange.

![image](https://user-images.githubusercontent.com/44687951/161792981-523732ca-e13f-499a-ba5d-2ae6eecf8480.png)

1 minute later, same request

![image](https://user-images.githubusercontent.com/44687951/161793412-69eda21c-70fb-4683-93b3-6c5cdedd758b.png)

**Comment by Donatas-MN** [comment]
Thanks! We will investigate this as well.

**Comment by Donatas-MN** [comment]
Node quality calculations were improved by:
1. Adding uptime to quality calculation.
2. Introducing more monitoring agents from different continents.
3. Fixing latency detection.
