### ISSUE TITLE
[windows] node gets into OnHold shortly after getting connected

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4809]
**Describe the bug**
Node gets into OnHold shortly after getting connected, connection lasts 1 minute or so.
Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8119069/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.1.6
 - OS: Windows

**Comment by portalsdevs** [comment]
More logs with hosting providers:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8125497/mysterium-node.log)

**Comment by etherunit** [comment]
Seeing this `2022-02-21T09:20:02.418 WRN source/communication/nats/connection_wrap.go:105 > NATS: disconnected error="read tcp 192.168.1.155:65075->51.15.116.186:4222: wsarecv: An established connection was aborted by the software in your host machine."`
right after state changed to connected. After connection abort it switches to OnHold because CLI value keep-connected-on-fail is set to true.

**Comment by etherunit** [comment]
Do you still notice this behaviour with [10.5.4](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/tag/10.6.3)?

**Comment by portalsdevs** [comment]
We haven't upgraded to 10.6.3 yet.
Was this fixed in this version?
