### ISSUE TITLE
Settlement not working

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4894]
**Describe the bug**

Total earnings did not increase to the balance after settlement, I also did a manual reset, but it didn't change the total value in the balance.

Node ID: [](https://app.intercom.com/#)0xe77282f63f416f4ac2a62a490e4ec1ad54432199

Logs:

https://mystnodes.com/support/logs/2022-03-18-b1a4329b-8690-4f92-ab6d-5b68debeb1c9-mysterium-node.zip4249549190

**Screenshots**

Before:
<img width="1264" alt="Screenshot 2022-03-18 at 03 58 02" src="https://user-images.githubusercontent.com/84313603/158952354-6e7fb750-9446-4c42-b220-809c63dddbca.png">

Later:
<img width="1327" alt="Screenshot 2022-03-18 at 03 58 41" src="https://user-images.githubusercontent.com/84313603/158952482-d376c3f0-017d-44ed-b4e7-dc57d14c4e9a.png">

<img width="1322" alt="Screenshot 2022-03-18 at 03 59 07" src="https://user-images.githubusercontent.com/84313603/158952494-ec983d4c-7603-44e7-82c7-cc9f110f8e02.png">

**Comment by tomasmik** [comment]
Did a proper node restart help or no?

**Comment by tomasmik** [comment]
The beneficiary seems to be not the persons channel address, but rather someone else's or his wallet. The money was settled and sent here: 0x77B6b0FC172d26FE8290EF831D94FeAd866aE5A3

You can see his beneficiary here: https://hermes.mysterium.network/api/v1/data/provider/0xe77282f63f416f4ac2a62a490e4ec1ad54432199

So it correct, his balance did not increase, but that is because he never sent the money to his balance.

**Comment by tomasmik** [comment]
After further checking, the person actually registered his node with a custom wallet which is not his channel
