### ISSUE TITLE
Settlement are to an unknown address

### ISSUE THREAD

**Issue by ffouqueray** [mysteriumnetwork/node#4943]
**Describe the bug**
Settlement are to an unknown address that I don't know the identity

**To Reproduce**
1. Go on your node
2. Click on settle button
3. Confirm it

**Expected behavior**
The money is added to my balance, and send to my top-up address

**Screenshots**
![identity](https://user-images.githubusercontent.com/65244389/160453099-517f632e-d641-46be-b4e8-525ad5f66739.png)
![polygonscan](https://user-images.githubusercontent.com/65244389/160453102-08b3108c-ca4a-4197-8018-87f2f508f477.png)
![settlements](https://user-images.githubusercontent.com/65244389/160453104-61baf66a-c329-42a4-b53e-7140877db0bb.png)

**Environment (please complete the following information):**
 - Node version: [1.6.0]
 - OS: [Ubuntu 20.04]
 - Your identity (if applicable): [0xf30d301b08694a6455c09d6141a7bf1304ef0438]

**Additional context**
I just dropped 7,8181283 MYST to an unknown address because there is anywhere in the configuration files this address entered and this is not mine (my external wallet is 0xa67F274926c6a84127FD92A33CE14D1Ec8a03d59)

In addition, Adine said me on discord that normally we don't see the address in a settlement. So there is a big bug on my node

Edit / Update : 
~~I got this problem since 1.4.11~~ to 1.6.0
After updated to 1.6.2, I activated the auto settlement to an external wallet, and tried to withdraw, all is working fine. But if I try again to settle to my node wallet, Idk if it will still be sent to this unknown wallet

**Comment by Guillembonet** [comment]
When you registered your identity in [this tx](https://polygonscan.com/tx/0x6148b21f4c306ae88288a23768693298b7a67ee407e68c6b53a2b665f3f2e333) you used a wallet belonging to another person (I think) as beneficiary, I really don't know what happened there but one possible explanation is that you had this address copied and pasted it there instead of your own, next settlements will be fine now. I see that the "unkown" wallet you used has withdrawals done by other identities like 0xf4399D1C028dda9C8058037a3D6E8aa54FEd821E or 0x7e4b0fd3a1728b918173e093572153b857c5d2fe. Maybe you recognise some of these.

**Comment by ffouqueray** [comment]
Yeah, maybe that. But why a settlement would go to the external wallet instead of the one of my node ? I searched in all my files to find the unknown wallet, and I didn't find anything about this.
