### ISSUE TITLE
mysterium.network does not use DNSSEC

### ISSUE THREAD

**Issue by MarkWieczorek** [mysteriumnetwork/node#5014]
The mysterium.network domain (including location, quality, and hermes) does not use DNSSEC. Given that this is a VPN service that cares about security, DNSSEC should probably turned on for this domain.

**Comment by etherunit** [comment]
regarding web traffic DNSSEC doesn't add security because we're relying on PKI of well-known certificate authorities for complete security of traffic. Share of DNSSEC-enabled domains only declines past years as they found it has not much adoption: https://blog.apnic.net/2018/08/17/sunrise-dns-over-tls-sunset-dnssec/
