### ISSUE TITLE
Node status problem and unreachable through app

### ISSUE THREAD

**Issue by sstealth01** [mysteriumnetwork/node#5162]
1) The last seen status on https://mystnodes.com/nodes is just showing '-' sign but the status says 'online'. When opening the nodeUI, 
     node status is 'Online' and NAT type is port restricted cone. (Refer attached)
2) Cannot find my node address when searching through mysterium VPN app on desktop or android.

The last seen status is working fine these few months and I have no other node FYI. Please fix this as I think it is also related as to why I cannot search my own node address (0xf8693200af9859cdf3743b21ccb84a0f42c0c5de) through both type of the mysterium VPN app and earning has gone down tremendously.

Attachments:
![image](https://user-images.githubusercontent.com/90108776/171396266-81a16bd5-1ea7-4da9-a134-53a559cdbfe0.png)

![image](https://user-images.githubusercontent.com/90108776/171396371-f4cd52e5-18fd-4dc4-8238-76c68a1c0243.png)

 - Node version: Alpine Linux v3.14(docker)
 - OS: docker desktop windows
 - Desktop app version: 10.9.0
 - Docker engine: v20.10.14 with image tag, [mysteriumnetwork/myst:latest]
 - Your identity: 0xf8693200af9859cdf3743b21ccb84a0f42c0c5de

**Comment by etherunit** [comment]
1. _The last seen status on https://mystnodes.com/nodes is just showing '-' sign but the status says 'online'. When opening the nodeUI, - it's how it works by design; If node is online, then it doesn't show "Last seen". 

2. It's being displayed here -> 0xf8693200af9859cdf3743b21ccb84a0f42c0c5de
<img width="640" alt="Screenshot 2022-06-05 at 14 48 51" src="https://user-images.githubusercontent.com/60128746/172049069-09777e6d-1937-4001-99a8-8e0507e58819.png">
