### ISSUE TITLE
Nodes not visible on Discovery

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5458]
**Describe the bug**

3 nodes installed are shown as online on nodeui but in the last seen is only a "-". Nodes are not visible in discovery https://discovery.mysterium.network/api/v3/proposals?provider_id= shows null for all 3. 

Node IDs:
0xd96200b4c419aaf074726a02390b433f636faa81
0x738f6b7e8762c6720b58e04e49f6bb2d558944db
0x4fbba0d89b6eeab8fbc8589441f7afba4673ac47

**Environment (please complete the following information):**

Node
In screenshot_2 called strato1
- Node version: 1.17.3
- OS: Ubuntu 20.04
- UI Version: 2.0.5
- Your identity (if applicable): 0xd96200b4c419aaf074726a02390b433f636faa81
- Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]
Node
In screenshot_2 called strato2
- Node version: 1.17.01
- OS: Ubuntu 20.04
- UI Version 2.0.3
- Your identity (if applicable): 0x738f6b7e8762c6720b58e04e49f6bb2d558944db
- Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]
Node
In screenshot_2 called strato3
- Node version: 1.17.3
- OS: Ubuntu 20.04
- UI Version: 2.0.5
- Your identity (if applicable): 0x4fbba0d89b6eeab8fbc8589441f7afba4673ac47
- Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

Logs:

https://mystnodes.com/support/logs/2022-09-21-3d2b6f81-dee1-4da6-915e-2b7c8adc3373-mysterium-node.zip2212436289

<img width="1207" alt="Screenshot 2022-09-21 at 13 07 51" src="https://user-images.githubusercontent.com/84313603/191555562-d06ec4bc-11ec-4a0e-a14d-cb9350de9918.png">

<img width="1326" alt="Screenshot 2022-09-21 at 13 10 12" src="https://user-images.githubusercontent.com/84313603/191555956-cffeddc4-3cab-48ae-acb1-4d006899a3ab.png">

**Comment by etherunit** [comment]
Eventually, nodes switched to connection_failed on mystnodes.com
After checking node logs, it's clear that further communication is failing due to 

`2022-09-19T23:21:03.759 ERR p2p/channel.go:425                       > Handler "p2p-session-create" internal error error="cannot start session: : cannot get provider config for session 0b38d502-75fa-4753-b1c6-9256523900f7: could not start new connection: could not start provider wg connection endpoint: could not configure device: failed to create TUN device: failed to create TUN device: permission denied"`

I suspect provider is running on a shared server with OpenVZ virtualization. 

### How to fix it?

1. Suggest provider to contact his hosting provider support and request to enable TUN/TAP virtual network adapter;
2. Grant rights to /dev/net/tun `chmod 777 /dev/net/tun`
3. Enabled userspace mode
