### ISSUE TITLE
Node quality dropped to 1 bar since update to 1.18.3

### ISSUE THREAD

**Issue by lollapalooza1973** [mysteriumnetwork/node#5535]
**Describe the bug**
Before the update to 1.18.3, my node had maximum quality in mystnodes.com
After updating to 1.18.1 - 1.18.2 - 1.18.3 on the same day, quality dropped to 1 bar only.
And since then, it's still 1 bar only.
From my side, nothing has been changed. ISP provides 1 Gbit down / 300 Mbit up; Raspberry is limited to 100 Mbit up/down.

I see clients are connecting and exchanging data, from many countried, with different session duration, and data exchanged that goes from 0 bytes to >1 GB.

**Expected behavior**
I expect to see 3 bars.

**Environment (please complete the following information):**
 - Node version: 1.18.3
 - OS: Mystberry
 - Your identity (if applicable): 0x4e29980147340362e66c58474ec2b2d79648d0c4

**Comment by lollapalooza1973** [comment]
Latency increased again; now it's 462 milliseconds.
I believe there's something wrong on how the latency is calculated by the Mysterium software.

This is a ping from the node (in EU) to Australia (opposite side of the world):
![image](https://user-images.githubusercontent.com/34000198/195353081-ec9e75ca-eb5d-4b39-99c4-143326657ba4.png)

**Comment by lollapalooza1973** [comment]
![image](https://user-images.githubusercontent.com/34000198/196026744-052eae3e-39c3-4f26-ab9b-a3bb6395c899.png)

**Comment by lollapalooza1973** [comment]
Getting worse.
![image](https://user-images.githubusercontent.com/34000198/196220398-aea7920a-dda2-40d9-a9b3-d4b5415fdd46.png)
![image](https://user-images.githubusercontent.com/34000198/196220471-e289715d-2878-4baa-ad1d-d2af11816664.png)

**Comment by lollapalooza1973** [comment]
Latency still increases day after day
![image](https://user-images.githubusercontent.com/34000198/196946292-c2f77105-295e-45dd-9fc6-4ec92622ace8.png)

**Comment by lollapalooza1973** [comment]
![image](https://user-images.githubusercontent.com/34000198/197122441-b522a567-decb-430a-aa0e-d4ce0b7e7be1.png)

**Comment by lollapalooza1973** [comment]
![image](https://user-images.githubusercontent.com/34000198/197217987-2d882a8c-2c27-47f6-9ff2-01bf1378df62.png)

**Comment by etherunit** [comment]
Please note that we are currently testing anti-abusing system, and your provider might get affected by this. If you are not doing any traffic manipulation your quality should recover soon.

**Comment by lollapalooza1973** [comment]
No traffic manipulation, dear @etherunit.
Maybe you don't believe me, but this is the truth. 
In this case you might connect to the node and verify by yourself.

I believe that your anti-abuse system doesn't work.

Latency increases day by day.

**Comment by Nitrooo** [comment]
Excuse me for the intrusion, I was following this issue and I can't help but notice one little thing. What is the point of inviting someone, after being caught, to test their node in the future if the fraudulent practices have been put in place in the past? It would be like receiving a speeding ticket and complaining to the policeman, with a shocked face, that the ticket is unfair because "tomorrow I will drive within the speed limit". Pardon me for being Captain Obvious, but maybe someone could benefit from a refresher in basic logic.

**Comment by lollapalooza1973** [comment]
Dear Captain Obvious, the latency keeps increasing, day by day, and there's no fraud (as far as I know).

Going back to the speeding example, it's like being stopped by police every day at speed *lower* than the limit, but being fined anyway because some time in the past (you don't know when, or any other detail) you've been *suspected* of speeding.

That's why I asked to test the node and understand why the latency increases each day.

Maybe there's something wrong with the node itself. Maybe it has been hacked?

Or maybe it's the fraud detection system being tested that doesn't work as expected?

I don't know.

What I know is that latency increases continuously, and quality is always very bad. And that there's no fraud, untile there's something I'm not aware of.

If, as you said, you "can't help", maybe it's useless to write a post just for polemics.

**Comment by Nitrooo** [comment]
You see, under different circumstances you might even be given the benefit of the doubt, except that I know for a fact that your node was purposely put under analysis a few days ago and a continuous and very high flow of unsolicited traffic was detected, most likely due to a `ping -f` command executed at the other end of the tunnel, since from the result of the analysis the traffic was almost perfectly symmetrical. Clearly this may have affected the quality of your node. In fact, by keeping an eye on your node quality after you were notified on the Discord server that your fraudulent behavior had been discovered, your node quality began to increase again. Evidently the traffic manipulation has been stopped. Have some more patience, stop these fraudulent practices once and for all, and you will see that your problems will be resolved. Thank you for your cooperation.

**Comment by lollapalooza1973** [comment]
I see that whatever I say seems just to be a way to justify what is unjustifiable.

But I just want to understand.

What I did a couple of days ago was to reboot the Raspberry. But still, since then, latency keeps increasing.
In less than 24 hours it went from 924 (that is a huge value) to 992, and I believe in 2-3 more days it will go well above 1000.

**Comment by lollapalooza1973** [comment]
Actually it took less than 2-3 days.
![immagine](https://user-images.githubusercontent.com/34000198/197332923-11ae5cd6-93f2-4ce1-bd26-6ad26aad758f.png)
![immagine](https://user-images.githubusercontent.com/34000198/197332937-48de9f74-309b-4fc0-a592-cfccc89be0e6.png)

And you still think this is because of scam. But I think this is because of a buggy "fraud detection" system.
Check again node stats and let me know.

**Comment by lollapalooza1973** [comment]
![immagine](https://user-images.githubusercontent.com/34000198/197352252-63a0704f-acff-4f63-a289-9d782133a7e2.png)

**Comment by etherunit** [comment]
I see there was no signals for the last 5 days 
![Screen Shot 2022-10-24 at 13 26 59](https://user-images.githubusercontent.com/60128746/197505859-6ff71af2-8028-4ea6-9f03-b03d4c54eb4c.png)
Based on that, it's safe to assume that quality should recoved in 1-2 days.
I can also see, that the only affected service left is data_transfer
see here: https://discovery.mysterium.network/api/v3/proposals?&access_policy=all&provider_id=0x4e29980147340362e66c58474ec2b2d79648d0c4
