### ISSUE TITLE
Node Status showing Online But Web "My Nodes" showing "Connection Failed"

### ISSUE THREAD

**Issue by pvarma01** [mysteriumnetwork/node#5625]
**Describe the bug**
Myst Node UI Node Status showing Online But Web "My Nodes" showing "Connection Failed"

**Comment by etherunit** [comment]
@pvarma01 What's your node identity?

**Comment by etherunit** [comment]
Thanks for adding node logs. From the first glance, it looks like all connection attempts fails due to:
`2022-10-22T13:44:18.423 DBG /source/core/service/subscription.go:70   > Received P2P session status message for "p2p-session-connectivity-status": ConsumerID:"0x098884ea8e949404c5cfe79fda74518c1e2c67af" SessionID:"f080e137-11eb-4d76-8a79-31bfa1b39ed3" Code:2003 Message:"could not start new connection: failed to start connection endpoint: could not configure device: DNS addr list is empty"`
**or**
`2022-10-19T02:26:48.564 DBG /source/core/service/subscription.go:70   > Received P2P session status message for "p2p-session-connectivity-status": ConsumerID:"0xcede8d3d07f96f5ff22847a530bcc86cfd168f17"  SessionID:"d60c7202-a053-42f3-ad50-e69dd9fd8d09"  Code:2003  Message:"failed to unmarshal connection config: invalid CIDR address: <nil>"`

@Zensey  Could you please take a look? `launcher.ver:1.0.34/windows` is in use.

**Comment by etherunit** [comment]
Curiously, my test connections worked as expected

```
» status
[INFO] Status:Connected
[INFO] SID:c051cb96-4970-4aa1-86c7-316391f10779
[INFO] Location: Mumbai, IN (residential - Syscon Infoway Pvt. Ltd.)
[INFO] Proposal:Provider: 0x42a1782f779f80b9cdf362507d92cd77095d7d4d, ServiceType: data_transfer, Country: IN
```
curl ipinfo.io
{
  "ip": "27.106.xxx",
  "city": "Mumbai",
  "region": "Maharashtra",
  "country": "IN",
  "loc": "19.0728,72.8826",
  "org": "AS136334 Vortex Netsol Private Limited",
  "postal": "400070",
  "timezone": "Asia/Kolkata",
  "readme": "https://ipinfo.io/missingauth"

**Comment by etherunit** [comment]
It seems related to https://github.com/mysteriumnetwork/node/issues/5627

**Comment by pvarma01** [comment]
Some Screen Shots Showing the connections.....
![Screenshot (1)](https://user-images.githubusercontent.com/118446543/203492976-5ea4862a-2741-498d-bc11-0811b0c09652.jpg)
![Screenshot (2)](https://user-images.githubusercontent.com/118446543/203492989-7ab35c36-8ef6-4f5d-9cc5-e7233603992c.jpg)

**Comment by etherunit** [comment]
@pvarma01  can see that provider has successfully updated launcher to the latest node release (1.19.7), however, it's still struggling to built connections. According to the node log output, it doesn't work with UDP hole punching, therefore I'd suggest switching to upnp (for testing purposes).

After zooming in, it looks like it helped. 

![Screen Shot 2022-12-13 at 08 51 34](https://user-images.githubusercontent.com/60128746/207246908-87d2fd9d-d515-4dd6-83c5-ed811c0cdeea.png)
