### ISSUE TITLE
Node status Monitoring failed

### ISSUE THREAD

**Issue by gitdawn69** [mysteriumnetwork/node#5651]
Node version:
1.19.5
Node UI version:
2.3.2

I installed it two days ago and got it running well yesterday, and this morning I noted the monitoring had failed during the night.
The browser says it's
![Screenshot 2022-11-28 092429](https://user-images.githubusercontent.com/119329822/204302088-c584e59b-c18f-402c-8279-80689ae83bef.png)
 dawn. The Mysterium Node Launcher says running

**Comment by etherunit** [comment]
Users of Mysterium Exit Node Launcher v.1.0.31 - 1.0.35 (WindowsOS): in order to upgrade to a new version v.1.0.37, it's required to download the MSI package from the following link: https://github.com/mysteriumnetwork/myst-launcher/releases/latest/download/myst-launcher-x64.msi

**Upgrade should fix Monitoring failed issues for Windows users with Native backend mode.** (https://github.com/mysteriumnetwork/node/pull/5640). 

Could you please try to upgrade to v1.0.17?
