### ISSUE TITLE
Problem monitoring failed , error again

### ISSUE THREAD

**Issue by gascanair** [mysteriumnetwork/node#5661]
Hello,
in the central panel for a month I have problems with Node on a raspberry os bullseye. I get this "monitoring failed" error and I don't understand why.
I posted this problem 10 days ago. after you repaired it, everything went ok for 4 days, and then this problem appeared again
![318283897_3374113692861196_8096811635199891901_n](https://user-images.githubusercontent.com/6025604/205511354-39c3a8a0-62c0-4387-ba11-2e30329df2b2.jpg)

Node version: 1.19.4
OS: bullseye 11 raspbian
Your identity (id node ): 0x65871e682a708751a4725130d574f8baafb8fbed
thanks

**Comment by etherunit** [comment]
From the first glance, it looks like node started to complain during switch from upnp to holepunching. I suspect upnp feature has been switched off due to some reasons? 

Could you try to re-enable it and check if that helps?

![Screen Shot 2022-12-07 at 14 28 05](https://user-images.githubusercontent.com/60128746/206179531-d1a4adbb-fecf-428c-bfb8-4a91432a8807.png)

**Comment by etherunit** [comment]
Please note that your node is online and working as expected. There was a switch to uPnP detected and therefore this might helped you.
![Screen Shot 2022-12-19 at 12 20 33](https://user-images.githubusercontent.com/60128746/208403500-03651953-02a7-4cf7-9cf3-c4f111d0168f.png)
