### ISSUE TITLE
something wrong with node bandwidth 

### ISSUE THREAD

**Issue by Sendros** [mysteriumnetwork/node#5721]
Hi, My internet speed is 1000/1000. However wen using my own node I can never get higher speeds then 30mbit.

I don't have the limit turned on in web interface. 
My node is: 0x612e1a6599281efe4f7abddffe9c10f289950410

**Comment by etherunit** [comment]
Hi @Sendros 
I've just tested your provider service from Amsterdam service and got the following results on the fly:

![Screen Shot 2023-01-25 at 09 05 09](https://user-images.githubusercontent.com/60128746/214501011-6150218a-e300-4df0-9aa2-059d6cb71d3c.png)
Having 30 - 50 Mbps should be fast enough to stream videos from standard to 4k HD definition as well as handling multiple connections.

**Comment by etherunit** [comment]
VPNs have a tendency to slow internet connections down. In reality there are a lot of things to consider: bandwidth limits and latency form the sources, server distance, the speed of your own and remote peers network, the protocol type in use, and etc. Imagine packets have to be encrypted and decrypted on the fly with a VPN tunnel causing a slow-down effect too. 
Overall, I consider your measured speed is quite good and there is nothing to worry about.

**Comment by Sendros** [comment]
> 

Hi Etherunit, 

thanks for your reply. i have some more questions. I understand its lower becasue of latency etc. But from 1000 to 100? and how com latency is 35ms? there is no datacenter in west Europe i cannot ping for under 10ms.

**Comment by etherunit** [comment]
Thanks for your question!

Usually speed test is performed via multiple TCP connections to some server. TCP protocol adjusts speed based on its perception of channel capacity, peers window size and latency. Here is some calculations for example: https://cordero.me/tcp-throughput-calculations/

Also transmission rate will be decreased if TCP stack observes packet loss: it doesn't distinguish between lost packets because of dropped packet due to exceeded bandwidth and packet dropped due to other (natural) reasons.

And, finally, internet is not uniform and available bandwidth is not the same in all directions. for example, connections within country may be fast, but there may be shortage of bandwidth in external directions due to limited total connectivity of that area. real world examples of such environments are isles, peninsulas and mainlands having incapacious connectivity.

All in all, apparent speed in the test may depend on following factors:

- minimal bandwidth on path to that server (for VPN case we should consider full path between client and final destination)
- packet loss rate
- method of test
- window size of established TCP connection
- hardware bottlenecks

Below is the example on how even slightest packet loss kills TCP performance:

![image (7)](https://user-images.githubusercontent.com/60128746/214774074-8379ce19-5723-4c85-9e3a-6d2f6d41cc66.png)

**Comment by Sendros** [comment]
Hi @etherunit, Thanks for your explanation. You can close the ticket.
