### ISSUE TITLE
Many 0kb connections

### ISSUE THREAD

**Issue by Sendros** [mysteriumnetwork/node#5722]
![image](https://user-images.githubusercontent.com/105081591/214397106-40b9e2ad-d9df-43f2-a458-a131d26f729d.png)
Im getting many 0kb connections.

node id: 0x612e1a6599281efe4f7abddffe9c10f289950410

**Comment by etherunit** [comment]
@Sendros Thanks for your report!
There was some failures with B2B data transfer service via your exit node, but from the current data, it looks stabilised (see picture below). 
+ We were doing some recalculations for the metrics, so it might had a short effect on the numbers which shouldnt be a case for now.
![Screen Shot 2023-01-26 at 08 53 52](https://user-images.githubusercontent.com/60128746/214775138-a6694a0e-5957-456c-ad79-d18040397080.png)

**Comment by guus461** [comment]
I have the same across all my nodes, many 0kb sessions

e.g. node id: 0x3c4fd61d7d2acd0022e612a0320fbd8e57dfd589

![image](https://user-images.githubusercontent.com/14141936/215104057-662f3ee2-d833-417d-9ba4-f03ceab09a40.png)

**Comment by etherunit** [comment]
Thanks @guus461 for submitting your screenshots!
Team will investigate this further and get back with an update here under comments.

**Comment by guus461** [comment]
> Thanks @guus461 for submitting your screenshots! Team will investigate this further and get back with an update here under comments.

Thanks!

**Comment by Sendros** [comment]
> Thanks @guus461 for submitting your screenshots! Team will investigate this further and get back with an update here under comments.

it still happands: 
![image](https://user-images.githubusercontent.com/105081591/215512111-6d429971-81f9-4c44-9193-a93a17c85047.png)

**Comment by etherunit** [comment]
I'm following up on this. I can confirm that we don't have any longer term issues with services that could potentially impact this. This is an outcome of consumers trying to connect to your without success. 

Most connections are successful and some of them fails due to the nature of network incompatibilities or other factors playing a role in building a VPN connection and transmitting encrypted data packets.

<img width="797" alt="Screen Shot 2023-02-01 at 08 56 42" src="https://user-images.githubusercontent.com/60128746/215973212-6b646128-669a-42ce-9110-cf4276cde61b.png">
<img width="800" alt="Screen Shot 2023-02-01 at 08 56 51" src="https://user-images.githubusercontent.com/60128746/215973214-4dd3fcf5-397a-4b7b-9138-ba06304de749.png">
<img width="809" alt="Screen Shot 2023-02-01 at 08 56 56" src="https://user-images.githubusercontent.com/60128746/215973216-54237b80-c929-4fd9-af32-d6e3d0eb8aab.png">
<img width="802" alt="Screen Shot 2023-02-01 at 08 57 01" src="https://user-images.githubusercontent.com/60128746/215973218-6c6c79cc-07d6-4674-8029-56a8bb36e96a.png">

**Comment by guus461** [comment]
Thanks
