### ISSUE TITLE
NAT Status is Open but Monitoring Failed, Traffic Was Good While On Pending

### ISSUE THREAD

**Issue by Xpl0itU** [mysteriumnetwork/node#6021]
**Describe the bug**
I setup a node and the NAT status is Open, but it still says Monitoring Failed, while its status was "Pending", I got some connections with significant bandwidth usage, but when it switched to Monitoring Failed, I either get none or really small bandwidth usage.

**Expected behavior**
Node Status should be Online and getting connections

**Screenshots**
![CleanShot 2024-03-20 at 15 25 08@2x](https://github.com/mysteriumnetwork/node/assets/24777100/b8cdc3fb-906b-4883-8799-3f3bacbb1f80)
![CleanShot 2024-03-20 at 15 29 44@2x](https://github.com/mysteriumnetwork/node/assets/24777100/65ec2147-e618-420a-a6cc-1c72ba2b85de)

**Environment (please complete the following information):**
 - Node version: 1.29.11
 - OS: Alpine Linux (Docker)
 - Docker (if applicable): mysteriumnetwork/myst:1.29.11-alpine
 - Your identity (if applicable): 0x7d48ee8c8438c44162969fde4930b0679cc5f97b

**Additional context**
I recently setup a DMZ pointing to the node and also enabled UPnP on the router too, so that the NAT could be open, I did all of this after setting up an initial node, and then removed the node and installed it again.

**Comment by PaJaSoft** [comment]
I just monitor that for last couple of days and I thing the root cause is soooo slow checking on the provider side nowadays.

I have also a node available for couple of days but even 'Test node' (from WebUI) passed (multiple times!), the node was still under the radar and claimed like 'Monitoring failed'/Online Red and https://discovery.mysterium.network/api/v3/proposals?include_monitoring_failed=true&provider_id=FOO didn't report it in the beginning, later with the filed about MONITORING_FAILED="true" or so, and couple of connection were served over this time without any issue. After 24+ (!)hours (wild guess is 28+) the first irregular check attempt was probably landed on my node and after that passed check whoala, my node is fully green (quality Green, Online Green). Obviously nothing changed on my Network side over that time...

**Comment by Xpl0itU** [comment]
> After 24+ (!)hours (wild guess is 28+) the first irregular check attempt was probably landed on my node and after that passed check whoala, my node is fully green (quality Green, Online Green).
Will try waiting then, if that works, I'll close this issue, thanks for your feedback

**Comment by Xpl0itU** [comment]
Closing this, waiting exactly 24 hours makes it magically go online and everything works just fine now
