### ISSUE TITLE
Minimal charge sum

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#723]
The AmountCalc needs to have a minimal charge concept. At the moment, we'll round down to 0 in some scenarios and that might not be the preferred way of handling the amount calculations.

Adding this as a separate task as this needs a thorough think.

**Comment by zolia** [comment]
We should not encourage service abuse, if some1 can get 59 seconds of free service even if service is paid, thats probably not ok. This may put a strain on a system, because of many frequent sessions setups. 
We may need to provide some test time for free, but need discussion on how to implement this.
