### ISSUE TITLE
Ubuntu 16.04 Node Failing to Start

### ISSUE THREAD

**Issue by geodavies** [mysteriumnetwork/node#8]
Some error seems to occur when starting the node via the service command. I get the following output from 'service mysterium-node status'.

`● mysterium-node.service - Server for decentralised VPN built on blockchain
   Loaded: loaded (/lib/systemd/system/mysterium-node.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-05-17 20:17:26 UTC; 9min ago
     Docs: https://mysterium.network/
  Process: 1312 ExecStart=/usr/bin/mysterium_server ${DAEMON_OPTS} (code=exited, status=1/FAILURE)
 Main PID: 1312 (code=exited, status=1/FAILURE)
      CPU: 0

May 17 20:17:26 ip-10-0-1-183 systemd[1]: Started Server for decentralised VPN built on blockchain.
May 17 20:17:26 ip-10-0-1-183 systemd[1]: mysterium-node.service: Main process exited, code=exited, status=1/FAILURE
May 17 20:17:26 ip-10-0-1-183 systemd[1]: mysterium-node.service: Unit entered failed state.
May 17 20:17:26 ip-10-0-1-183 systemd[1]: mysterium-node.service: Failed with result 'exit-code'.
May 17 20:17:26 ip-10-0-1-183 systemd[1]: mysterium-node.service: Service hold-off time over, scheduling restart.
May 17 20:17:26 ip-10-0-1-183 systemd[1]: Stopped Server for decentralised VPN built on blockchain.
May 17 20:17:26 ip-10-0-1-183 systemd[1]: mysterium-node.service: Start request repeated too quickly.
May 17 20:17:26 ip-10-0-1-183 systemd[1]: Failed to start Server for decentralised VPN built on blockchain.
May 17 20:17:26 ip-10-0-1-183 systemd[1]: mysterium-node.service: Unit entered failed state.
May 17 20:17:26 ip-10-0-1-183 systemd[1]: mysterium-node.service: Failed with result 'exit-code'.
`

Are there any log files I can look at so see if I can find the root of the failure. The status is not very descriptive.

**Comment by Hostile** [comment]
same on ubuntu 16.04

**Comment by Waldz** [comment]
Thanks for detailed description, we will fix it.

Problem is because You try to start Service via Systemd.
Currently it was tested only with Initd:
```
/etc/init.d/mysterium-node start
```

**Comment by Hostile** [comment]
thx

**Comment by geodavies** [comment]
It appears as though the .deb file only installs with systemd as when I run the command you suggested I get: '/etc/init.d/mysterium-node: No such file or directory'

I've had a look inside of of the init.d directory and can confirm it's not there.

I have also tried running with 'systemctl start mysterium_node' but get a similar issue of 'Unit mysterium_node.service could not be found.'

**Comment by ewrogers** [comment]
Confirmed to be an issue on 16.04. There appears to be two problems:

- `root` is required to run `iptables`, service runes as `mysterious-node`
- Not sure where `${DAEMON_OPTS}` are injected from, but do not seem to work.

My workaround is to manually edit the `/lib/systemd/system/mysterium-node.service` file like so (replacing `NODE_KEY` with your own):

`[Unit]
Description=Server for decentralised VPN built on blockchain
Documentation=https://mysterium.network/
After=network-online.target

[Service]
# User=mysterium-node
# Group=mysterium-node
WorkingDirectory=/etc/mysterium-node
ExecStart=/usr/bin/mysterium_server --node=NODE_KEY --runtime-dir /tmp
KillMode=control-group
Restart=on-failure

[Install]
WantedBy=multi-user.target`

Did a reboot and now the service is running without issue.

**Comment by Waldz** [comment]
Exact starting command should be like this:
```
sudo /usr/bin/mysterium_server --node=NODE_KEY --config-dir=/etc/mysterium-node --runtime-dir=/var/run/mysterium-node
```

**Comment by hubiktomas** [comment]
Same problem here with Debian 8.8 - manually changing systemd startup script worked.

**Comment by princevince** [comment]
This is what I get when running from the command-line:

> 1495313522082784450 [Info] [ipify.api] IP detected: <my-public-ip-address>
> 1495313522083917601 [Info] [nat] IP forwarding enabled
> 1495313522084779221 [Info] [nat] Forwarding packets from '10.8.0.0/24' to IP: <my-public-ip-address>
> listen unix /var/run/mysterium-node/openvpn-management-4ec7ba0nat.sock: bind: no such file or directory

**Comment by hubiktomas** [comment]
I had the same problem. Just create the mysterium-node directory if it is not there and it should work. It is a workaround for a problem that is there.

**Comment by princevince** [comment]
Thanks! That worked.

**Comment by seamlik** [comment]
Please fix this bug ASAP, or it just blocks more volunteers from trying. Ubuntu and Debian already uses systemd now, testing it on systemd should have been the top priority.

**Comment by geodavies** [comment]
Can confirm the temporary fix suggested by @ewrogers worked for me also.

**Comment by fnzv** [comment]
@geodavies The workaround works but how its safe to run as root?

**Comment by ewrogers** [comment]
You should be using the docker container for proper isolation.

**Comment by ne0ark** [comment]
Be aware that 16.04 will start the mysterium but !check will fail best way is to start it using sudo /usr/bin/mysterium_server --node=NODE_KEY --config-dir=/etc/mysterium-node --runtime-dir=/var/run/mysterium-node

**Comment by Nipol** [comment]
Clearing.

```
[Unit]
Description=Server for decentralised VPN built on blockchain
Documentation=https://mysterium.network/
After=network-online.target

[Service]
# User=mysterium-node
# Group=mysterium-node
WorkingDirectory=/etc/mysterium-node
ExecStart=/usr/bin/mysterium_server --node=NODE_KEY --config-dir=/etc/mysterium-node --runtime-dir=/var/run/mysterium-node
KillMode=control-group
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

reboot. or reload.

```
sudo mkdir /var/run/mysterium-node
sudo service mysterium-node start
sudo service mysterium-node status
```

check.

**Comment by cricket007** [comment]
Alternative solution, actually define `DAEMON_OPTS`

```
$ sudo cat /etc/default/mysterium-node 
MYSTERIUM_SERVER_NODE=
MYSTERIUM_SERVER_CONF_DIR=/etc/mysterium-node
MYSTERIUM_SERVER_RUN_DIR=/var/run/mysterium-node
DAEMON_OPTS="--node=$MYSTERIUM_SERVER_NODE --config-dir=$MYSTERIUM_SERVER_CONF_DIR --runtime-dir=$MYSTERIUM_SERVER_RUN_DIR"
```

**Comment by lmnope1** [comment]
Never been fixed

**Comment by sanox1** [comment]
I recevie similar error after running apt-get upgrade yesterday : 

systemctl status mysterium-node.service
Б≈▐ mysterium-node.service - Server for Mysterium - decentralised VPN Network
   Loaded: loaded (/lib/systemd/system/mysterium-node.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2024-01-29 08:28:17 GMT; 3s ago
     Docs: https://mysterium.network/
  Process: 6148 ExecStart=/usr/bin/myst $CONF_DIR $SCRIPT_DIR $DATA_DIR $RUN_DIR $DAEMON_OPTS --ui.features=restart service --agreed-terms-and-conditions $SERVICE_OPTS
 Main PID: 6148 (code=exited, status=2)

Jan 29 08:28:17 raspberrypi myst[6148]: runtime.goPanicIndex(0x3d56244f, 0x100000)
Jan 29 08:28:17 raspberrypi myst[6148]:         /usr/lib/go-1.20/src/runtime/panic.go:112 +0x2c fp=0x7e8d2838 sp=0x7e8d2818 pc=0x50f3c
Jan 29 08:28:17 raspberrypi myst[6148]: runtime.gentraceback(0x485c44, 0x3e1f88c, 0x0, 0x3c020f0, 0x3, 0x4004000, 0x20, 0x0, 0x0, 0x0)
Jan 29 08:28:17 raspberrypi myst[6148]:         /usr/lib/go-1.20/src/runtime/traceback.go:366 +0x186c fp=0x7e8d2a3c sp=0x7e8d2838 pc=0x7fd0c
Jan 29 08:28:17 raspberrypi myst[6148]: runtime.callers.func1()
Jan 29 08:28:17 raspberrypi myst[6148]:         /usr/lib/go-1.20/src/runtime/traceback.go:844 +0x74 fp=0x7e8d2a70 sp=0x7e8d2a3c pc=0x811bc
Jan 29 08:28:17 raspberrypi myst[6148]: runtime.systemstack()
Jan 29 08:28:17 raspberrypi myst[6148]:         /usr/lib/go-1.20/src/runtime/asm_arm.s:317 +0x60 fp=0x7e8d2a74 sp=0x7e8d2a70 pc=0x8d4a4
Jan 29 08:28:17 raspberrypi systemd[1]: mysterium-node.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 29 08:28:17 raspberrypi systemd[1]: mysterium-node.service: Failed with result 'exit-code'.

my config looks like this : 

[Unit]
Description=Server for Mysterium - decentralised VPN Network
Documentation=https://mysterium.network/
Requires=network-online.target
After=network-online.target

[Service]
User=mysterium-node
Group=mysterium-node

RuntimeDirectory=mysterium-node
RuntimeDirectoryMode=0750
LogsDirectory=mysterium-node

EnvironmentFile=-/etc/default/mysterium-node
ExecStart=/usr/bin/myst \
    $CONF_DIR \
    $SCRIPT_DIR \
    $DATA_DIR \
    $RUN_DIR \
    $DAEMON_OPTS \
    --ui.features=restart \
    service \
    --agreed-terms-and-conditions \
    $SERVICE_OPTS
KillMode=process
SendSIGKILL=yes
Restart=on-failure
RestartSec=5
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target


please advise how to modify so that it runs again ? Thanks
